#ifndef CANBUSCONTROL_H
#define CANBUSCONTROL_H

#include <QObject>
#include <QString>
#include <QByteArray>
#include <vector>
#include <string>
#include <QJsonObject>
#include <QStringList>
#include "model/canbusgc.h"
#include "model/canbuszlg.h"
#include "model/canbusfxynew.h"
#include "model/canbusfxyold.h"
#include "model/testitemenums.h"
#include "model/Rs485RingBuf.h"
#include <QThread>
#include <atomic>
#include "model/timer.h"
#include "excelcontrol.h"
#include "model/cangetandsend.h"
#include "include/ControlCAN.h"

class CanRxParseThread : public QThread
{
    Q_OBJECT
public:
    CanRxParseThread() = default;
    ~CanRxParseThread() override;

    // 启停线程
    void StartParse();
    void StopParse();

signals:
    // 可选：解析完成抛信号给UI刷新
    void sigNewRxFrame(const PVCI_CAN_OBJ& frame);

private:
    std::atomic<bool> m_running{false};

protected:
    void run() override;
};

class QTimer;
class Ping;
class CanBusControl : public QObject
{
    Q_OBJECT
public:
    CanBusControl(int type, int id, int pass, int port);
    ~CanBusControl();
    void testConn();
    bool isFinish(int status);
    int currentTestStep();
    void setType(int type1, int type2, int type3, int type4, int type5, int type6, int type7, int type8, int type9
                 , int type10, int type11, int type12, int type13, int type14, int type15, int type16);
    void testJson();

private:
    void TransmitCAN(int ID, unsigned char data[8]);
    void unsigned_to_hex(unsigned int value, std::string& hex_string);

private:
    CanRxParseThread g_rxParseThread;
    int canType;
    int deviceType;
    int m_locate;
    int m_pass;
    int m_port;
    int m_type1;
    int m_type2;
    int m_type3;
    int m_type4;
    int m_type5;
    int m_type6;
    int m_type7;
    int m_type8;
    int m_type9;
    int m_type10;
    int m_type11;
    int m_type12;
    int m_type13;
    int m_type14;
    int m_type15;
    int m_type16;
    QString m_serial1;
    QString m_serial2;
    QString m_serial3;
    QString m_serial4;
    QString m_serial5;
    QString m_serial6;
    QString m_serial7;
    QString m_serial8;
    QString m_serial9;
    QString m_serial10;
    QString m_serial11;
    QString m_serial12;
    QString m_serial13;
    QString m_serial14;
    QString m_serial15;
    QString m_serial16;
    QByteArray receiveArray1;
    QByteArray receiveArray2;
    QByteArray receiveArray3;
    QByteArray receiveArray4;
    QByteArray receiveArray5;
    QByteArray receiveArray6;
    QByteArray receiveArray7;
    QByteArray receiveArray8;
    QByteArray receiveArray9;
    QByteArray receiveArray10;
    QByteArray receiveArray11;
    QByteArray receiveArray12;
    QByteArray receiveArray13;
    QByteArray receiveArray14;
    QByteArray receiveArray15;
    QByteArray receiveArray16;
    LCANBusFXYOLD *canBusFO1;   //旧版分析仪
    LCANBusFXYNEW *canBusFN1;   //新版分析仪
    LCANBusZLG *canBusZLG1;     //周立功CAN卡
    LCANBusGC *canBusGC1;       //广成CAN卡
    LCANBusFXYOLD *canBusFO2;   //旧版分析仪
    LCANBusFXYNEW *canBusFN2;   //新版分析仪
    LCANBusZLG *canBusZLG2;     //周立功CAN卡
    LCANBusGC *canBusGC2;       //广成CAN卡
    QByteArray currentData;
    int step = 0;
    std::vector<ExcelItem> items;
    QStringList m_macList;
    QString m_serial;
    QString serial_receive;
    QString m_software;
    QString m_hardware;
    QTimer *testTimer = NULL;
    bool ifCanPass = true;
    bool ifVPass = true;
    bool ifRPass = true;
    bool ifCPass = true;
    QByteArray receiveArray;
    QByteArray hardwareArray;
    QByteArray nameArray;
    int canTime = 0;
    bool if_mes = false;
    CANGetAndSend *can1;
    CANGetAndSend *can2;
    CANGetAndSend *can3;
    CANGetAndSend *can4;
    CANGetAndSend *can5;
    CANGetAndSend *can6;
    CANGetAndSend *can7;
    CANGetAndSend *can8;
    CANGetAndSend *can9;
    CANGetAndSend *can10;
    CANGetAndSend *can11;
    CANGetAndSend *can12;
    CANGetAndSend *can13;
    CANGetAndSend *can14;
    CANGetAndSend *can15;
    CANGetAndSend *can16;
    bool ifTesting1 = false;
    bool ifTesting2 = false;
    bool ifTesting3 = false;
    bool ifTesting4 = false;
    bool ifTesting5 = false;
    bool ifTesting6 = false;
    bool ifTesting7 = false;
    bool ifTesting8 = false;
    bool ifTesting9 = false;
    bool ifTesting10 = false;
    bool ifTesting11 = false;
    bool ifTesting12 = false;
    bool ifTesting13 = false;
    bool ifTesting14 = false;
    bool ifTesting15 = false;
    bool ifTesting16 = false;

    bool ifCanUpdate1 = false;
    bool ifCanUpdate2 = false;
    bool ifCanUpdate3 = false;
    bool ifCanUpdate4 = false;
    bool ifCanUpdate5 = false;
    bool ifCanUpdate6 = false;
    bool ifCanUpdate7 = false;
    bool ifCanUpdate8 = false;
    bool ifCanUpdate9 = false;
    bool ifCanUpdate10 = false;
    bool ifCanUpdate11 = false;
    bool ifCanUpdate12 = false;
    bool ifCanUpdate13 = false;
    bool ifCanUpdate14 = false;
    bool ifCanUpdate15 = false;
    bool ifCanUpdate16 = false;
    bool if_test1 = true;
    bool if_test2 = true;
    bool if_test3 = true;
    bool if_test4 = true;
    bool if_test5 = true;
    bool if_test6 = true;
    bool if_test7 = true;
    bool if_test8 = true;
    bool if_test9 = true;
    bool if_test10 = true;
    bool if_test11 = true;
    bool if_test12 = true;
    bool if_test13 = true;
    bool if_test14 = true;
    bool if_test15 = true;
    bool if_test16 = true;
    int m_info = 0;
    Rs485ParseThread m_rs485Parse;

public slots:
    void slotCANStatus(CANFXYOLDRETURNCODE status);
    void slotCANStatus(CANFXYNEWRETURNCODE status);
    void slotCANStatus(CANZLGRETURNCODE status);
    void slotCANStatus(CANGCRETURNCODE status);
    void slotReceiveData(VCI_CAN_OBJ pReceive);
    void slotReceiveData(CAN_OBJ pReceive);
    void slotReceiveData2(VCI_CAN_OBJ pReceive);
    void slotReceiveData2(CAN_OBJ pReceive);
    void slotChooseZLGType(int type);
    void slotChooseGCType(int type);
    void updateTestItem1();
    void updateTestItem2();
    void updateTestItem3();
    void updateTestItem4();
    void updateTestItem5();
    void updateTestItem6();
    void updateTestItem7();
    void updateTestItem8();
    void updateTestItem9();
    void updateTestItem10();
    void updateTestItem11();
    void updateTestItem12();
    void updateTestItem13();
    void updateTestItem14();
    void updateTestItem15();
    void updateTestItem16();
    void slotMac(const QString &mac);
    void slotSetSerial(const QString &serial);
    void slotSetCurrentTestStep1(int type);
    void slotSetCurrentTestStep2(int type);
    void slotSetCurrentTestStep3(int type);
    void slotSetCurrentTestStep4(int type);
    void slotSetCurrentTestStep5(int type);
    void slotSetCurrentTestStep6(int type);
    void slotSetCurrentTestStep7(int type);
    void slotSetCurrentTestStep8(int type);
    void slotSetCurrentTestStep9(int type);
    void slotSetCurrentTestStep10(int type);
    void slotSetCurrentTestStep11(int type);
    void slotSetCurrentTestStep12(int type);
    void slotSetCurrentTestStep13(int type);
    void slotSetCurrentTestStep14(int type);
    void slotSetCurrentTestStep15(int type);
    void slotSetCurrentTestStep16(int type);
    void slotSetSoft(const QString &id);
    void slotSetHard(const QString &id);
    void slotSetMod(bool mod);
    void slotFinish1();
    void slotFinish2();
    void slotFinish3();
    void slotFinish4();
    void slotFinish5();
    void slotFinish6();
    void slotFinish7();
    void slotFinish8();
    void slotFinish9();
    void slotFinish10();
    void slotFinish11();
    void slotFinish12();
    void slotFinish13();
    void slotFinish14();
    void slotFinish15();
    void slotFinish16();
    void slotErrorFinish1();
    void slotErrorFinish2();
    void slotErrorFinish3();
    void slotErrorFinish4();
    void slotErrorFinish5();
    void slotErrorFinish6();
    void slotErrorFinish7();
    void slotErrorFinish8();
    void slotErrorFinish9();
    void slotErrorFinish10();
    void slotErrorFinish11();
    void slotErrorFinish12();
    void slotErrorFinish13();
    void slotErrorFinish14();
    void slotErrorFinish15();
    void slotErrorFinish16();
    void slotCheckStatus();
    void slotTransmitCAN(PVCI_CAN_OBJ pSend, ULONG Len);
    void slotTransmitCAN(CAN_OBJ pSend, ULONG Len);
    void slotTestResult1(bool result);
    void slotTestResult2(bool result);
    void slotTestResult3(bool result);
    void slotTestResult4(bool result);
    void slotTestResult5(bool result);
    void slotTestResult6(bool result);
    void slotTestResult7(bool result);
    void slotTestResult8(bool result);
    void slotTestResult9(bool result);
    void slotTestResult10(bool result);
    void slotTestResult11(bool result);
    void slotTestResult12(bool result);
    void slotTestResult13(bool result);
    void slotTestResult14(bool result);
    void slotTestResult15(bool result);
    void slotTestResult16(bool result);
    void slotSerialError1();
    void slotSerialError2();
    void slotSerialError3();
    void slotSerialError4();
    void slotSerialError5();
    void slotSerialError6();
    void slotSerialError7();
    void slotSerialError8();
    void slotSerialError9();
    void slotSerialError10();
    void slotSerialError11();
    void slotSerialError12();
    void slotSerialError13();
    void slotSerialError14();
    void slotSerialError15();
    void slotSerialError16();
    void slotStartTest1();
    void slotStartTest2();
    void slotStartTest3();
    void slotStartTest4();
    void slotStartTest5();
    void slotStartTest6();
    void slotStartTest7();
    void slotStartTest8();
    void slotStartTest9();
    void slotStartTest10();
    void slotStartTest11();
    void slotStartTest12();
    void slotStartTest13();
    void slotStartTest14();
    void slotStartTest15();
    void slotStartTest16();
    void slotSetTestMod1();
    void slotSetTestMod2();
    void slotSetTestMod3();
    void slotSetTestMod4();
    void slotSetTestMod5();
    void slotSetTestMod6();
    void slotSetTestMod7();
    void slotSetTestMod8();
    void slotSetTestMod9();
    void slotSetTestMod10();
    void slotSetTestMod11();
    void slotSetTestMod12();
    void slotSetTestMod13();
    void slotSetTestMod14();
    void slotSetTestMod15();
    void slotSetTestMod16();
    void slotSetSerial1(QString serial);
    void slotSetSerial2(QString serial);
    void slotSetSerial3(QString serial);
    void slotSetSerial4(QString serial);
    void slotSetSerial5(QString serial);
    void slotSetSerial6(QString serial);
    void slotSetSerial7(QString serial);
    void slotSetSerial8(QString serial);
    void slotSetSerial9(QString serial);
    void slotSetSerial10(QString serial);
    void slotSetSerial11(QString serial);
    void slotSetSerial12(QString serial);
    void slotSetSerial13(QString serial);
    void slotSetSerial14(QString serial);
    void slotSetSerial15(QString serial);
    void slotSetSerial16(QString serial);
    void slotSetMAC1(QString serial);
    void slotSetMAC2(QString serial);
    void slotSetMAC3(QString serial);
    void slotSetMAC4(QString serial);
    void slotSetMAC5(QString serial);
    void slotSetMAC6(QString serial);
    void slotSetMAC7(QString serial);
    void slotSetMAC8(QString serial);
    void slotSetMAC9(QString serial);
    void slotSetMAC10(QString serial);
    void slotSetMAC11(QString serial);
    void slotSetMAC12(QString serial);
    void slotSetMAC13(QString serial);
    void slotSetMAC14(QString serial);
    void slotSetMAC15(QString serial);
    void slotSetMAC16(QString serial);
    void slotSetExcelItem1(std::vector<ExcelItem> items);
    void slotSetExcelItem2(std::vector<ExcelItem> items);
    void slotSetExcelItem3(std::vector<ExcelItem> items);
    void slotSetExcelItem4(std::vector<ExcelItem> items);
    void slotSetExcelItem5(std::vector<ExcelItem> items);
    void slotSetExcelItem6(std::vector<ExcelItem> items);
    void slotSetExcelItem7(std::vector<ExcelItem> items);
    void slotSetExcelItem8(std::vector<ExcelItem> items);
    void slotSetExcelItem9(std::vector<ExcelItem> items);
    void slotSetExcelItem10(std::vector<ExcelItem> items);
    void slotSetExcelItem11(std::vector<ExcelItem> items);
    void slotSetExcelItem12(std::vector<ExcelItem> items);
    void slotSetExcelItem13(std::vector<ExcelItem> items);
    void slotSetExcelItem14(std::vector<ExcelItem> items);
    void slotSetExcelItem15(std::vector<ExcelItem> items);
    void slotSetExcelItem16(std::vector<ExcelItem> items);
    void slotReceiveStatus1(const QString &status);
    void slotReceiveStatus2(const QString &status);
    void slotReceiveStatus3(const QString &status);
    void slotReceiveStatus4(const QString &status);
    void slotReceiveStatus5(const QString &status);
    void slotReceiveStatus6(const QString &status);
    void slotReceiveStatus7(const QString &status);
    void slotReceiveStatus8(const QString &status);
    void slotReceiveStatus9(const QString &status);
    void slotReceiveStatus10(const QString &status);
    void slotReceiveStatus11(const QString &status);
    void slotReceiveStatus12(const QString &status);
    void slotReceiveStatus13(const QString &status);
    void slotReceiveStatus14(const QString &status);
    void slotReceiveStatus15(const QString &status);
    void slotReceiveStatus16(const QString &status);

    void slotSendTestResult1(QJsonObject data);
    void slotSendTestResult2(QJsonObject data);
    void slotSendTestResult3(QJsonObject data);
    void slotSendTestResult4(QJsonObject data);
    void slotSendTestResult5(QJsonObject data);
    void slotSendTestResult6(QJsonObject data);
    void slotSendTestResult7(QJsonObject data);
    void slotSendTestResult8(QJsonObject data);
    void slotSendTestResult9(QJsonObject data);
    void slotSendTestResult10(QJsonObject data);
    void slotSendTestResult11(QJsonObject data);
    void slotSendTestResult12(QJsonObject data);
    void slotSendTestResult13(QJsonObject data);
    void slotSendTestResult14(QJsonObject data);
    void slotSendTestResult15(QJsonObject data);
    void slotSendTestResult16(QJsonObject data);

    void slotSetModFail1();
    void slotSetModFail2();
    void slotSetModFail3();
    void slotSetModFail4();
    void slotSetModFail5();
    void slotSetModFail6();
    void slotSetModFail7();
    void slotSetModFail8();
    void slotSetModFail9();
    void slotSetModFail10();
    void slotSetModFail11();
    void slotSetModFail12();
    void slotSetModFail13();
    void slotSetModFail14();
    void slotSetModFail15();
    void slotSetModFail16();

    void slotTimeout1();
    void slotTimeout2();
    void slotTimeout3();
    void slotTimeout4();
    void slotTimeout5();
    void slotTimeout6();
    void slotTimeout7();
    void slotTimeout8();
    void slotTimeout9();
    void slotTimeout10();
    void slotTimeout11();
    void slotTimeout12();
    void slotTimeout13();
    void slotTimeout14();
    void slotTimeout15();
    void slotTimeout16();

    void slotSetModFail21();
    void slotSetModFail22();
    void slotSetModFail23();
    void slotSetModFail24();
    void slotSetModFail25();
    void slotSetModFail26();
    void slotSetModFail27();
    void slotSetModFail28();
    void slotSetModFail29();
    void slotSetModFail210();
    void slotSetModFail211();
    void slotSetModFail212();
    void slotSetModFail213();
    void slotSetModFail214();
    void slotSetModFail215();
    void slotSetModFail216();

    void slotFinishSet1();
    void slotFinishSet2();
    void slotFinishSet3();
    void slotFinishSet4();
    void slotFinishSet5();
    void slotFinishSet6();
    void slotFinishSet7();
    void slotFinishSet8();
    void slotFinishSet9();
    void slotFinishSet10();
    void slotFinishSet11();
    void slotFinishSet12();
    void slotFinishSet13();
    void slotFinishSet14();
    void slotFinishSet15();
    void slotFinishSet16();

    void slotFinishSet21();
    void slotFinishSet22();
    void slotFinishSet23();
    void slotFinishSet24();
    void slotFinishSet25();
    void slotFinishSet26();
    void slotFinishSet27();
    void slotFinishSet28();
    void slotFinishSet29();
    void slotFinishSet210();
    void slotFinishSet211();
    void slotFinishSet212();
    void slotFinishSet213();
    void slotFinishSet214();
    void slotFinishSet215();
    void slotFinishSet216();
    void slotReadKB(int cf, int type, int locate);
    void slotSetKB(int cf, int type, float k, float b, int locate);
    void slotReadInfo(int type, int locate);
    void slotOpenDO(int locate);
    void slotCloseDO(int locate);
    void slotChange(int type, int locate);

    void slotSetUpdateStatus1(bool status);
    void slotSetUpdateStatus2(bool status);
    void slotSetUpdateStatus3(bool status);
    void slotSetUpdateStatus4(bool status);
    void slotSetUpdateStatus5(bool status);
    void slotSetUpdateStatus6(bool status);
    void slotSetUpdateStatus7(bool status);
    void slotSetUpdateStatus8(bool status);
    void slotSetUpdateStatus9(bool status);
    void slotSetUpdateStatus10(bool status);
    void slotSetUpdateStatus11(bool status);
    void slotSetUpdateStatus12(bool status);
    void slotSetUpdateStatus13(bool status);
    void slotSetUpdateStatus14(bool status);
    void slotSetUpdateStatus15(bool status);
    void slotSetUpdateStatus16(bool status);

    void slotCheckIfCanUpdate1();
    void slotCheckIfCanUpdate2();
    void slotCheckIfCanUpdate3();
    void slotCheckIfCanUpdate4();
    void slotCheckIfCanUpdate5();
    void slotCheckIfCanUpdate6();
    void slotCheckIfCanUpdate7();
    void slotCheckIfCanUpdate8();
    void slotCheckIfCanUpdate9();
    void slotCheckIfCanUpdate10();
    void slotCheckIfCanUpdate11();
    void slotCheckIfCanUpdate12();
    void slotCheckIfCanUpdate13();
    void slotCheckIfCanUpdate14();
    void slotCheckIfCanUpdate15();
    void slotCheckIfCanUpdate16();

signals:
    void signalChooseZLGDeviceType();
    void signalChooseGCDeviceType();
    void signalOpenCAN(int m_devtypeno, int m_devindexno);
    void signalCloseCAN(int m_devtypeno, int m_devindexno);
    void signalStartCAN(int m_devtypeno, int m_devindexno, int m_devCANIndex, int port);
    void signalResetCAN(int m_devtypeno, int m_devindexno, int m_devCANIndex);
    void signalInitCAN(int m_devtypeno, int m_devindexno, int m_devCANIndex);
    void signalOpenCAN2(int m_devtypeno, int m_devindexno);
    void signalCloseCAN2(int m_devtypeno, int m_devindexno);
    void signalStartCAN2(int m_devtypeno, int m_devindexno, int m_devCANIndex, int port);
    void signalResetCAN2(int m_devtypeno, int m_devindexno, int m_devCANIndex);
    void signalInitCAN2(int m_devtypeno, int m_devindexno, int m_devCANIndex);
    void signalTransmitCAN(int m_devtypeno, int m_devindexno, int m_devCANIndex, PVCI_CAN_OBJ pSend, ULONG Len);
    void signalTransmitCAN(int m_devtypeno, int m_devindexno, int m_devCANIndex, CAN_OBJ pSend, ULONG Len);
    void signalReceiveStatus1(const QString &);
    void signalReceiveStatus2(const QString &);
    void signalReceiveStatus3(const QString &);
    void signalReceiveStatus4(const QString &);
    void signalReceiveStatus5(const QString &);
    void signalReceiveStatus6(const QString &);
    void signalReceiveStatus7(const QString &);
    void signalReceiveStatus8(const QString &);
    void signalReceiveStatus9(const QString &);
    void signalReceiveStatus10(const QString &);
    void signalReceiveStatus11(const QString &);
    void signalReceiveStatus12(const QString &);
    void signalReceiveStatus13(const QString &);
    void signalReceiveStatus14(const QString &);
    void signalReceiveStatus15(const QString &);
    void signalReceiveStatus16(const QString &);
    void signalReceiveErrorStatus(const QString &);
    void singalReceiveMAC(const QString &);
    void signalFinish1();
    void signalFinish2();
    void signalFinish3();
    void signalFinish4();
    void signalFinish5();
    void signalFinish6();
    void signalFinish7();
    void signalFinish8();
    void signalFinish9();
    void signalFinish10();
    void signalFinish11();
    void signalFinish12();
    void signalFinish13();
    void signalFinish14();
    void signalFinish15();
    void signalFinish16();
    void signalErrorFinish1();
    void signalErrorFinish2();
    void signalErrorFinish3();
    void signalErrorFinish4();
    void signalErrorFinish5();
    void signalErrorFinish6();
    void signalErrorFinish7();
    void signalErrorFinish8();
    void signalErrorFinish9();
    void signalErrorFinish10();
    void signalErrorFinish11();
    void signalErrorFinish12();
    void signalErrorFinish13();
    void signalErrorFinish14();
    void signalErrorFinish15();
    void signalErrorFinish16();
    void signalSetCurrentTestStep1(int);
    void signalSetCurrentTestStep2(int);
    void signalSetCurrentTestStep3(int);
    void signalSetCurrentTestStep4(int);
    void signalSetCurrentTestStep5(int);
    void signalSetCurrentTestStep6(int);
    void signalSetCurrentTestStep7(int);
    void signalSetCurrentTestStep8(int);
    void signalSetCurrentTestStep9(int);
    void signalSetCurrentTestStep10(int);
    void signalSetCurrentTestStep11(int);
    void signalSetCurrentTestStep12(int);
    void signalSetCurrentTestStep13(int);
    void signalSetCurrentTestStep14(int);
    void signalSetCurrentTestStep15(int);
    void signalSetCurrentTestStep16(int);
    void signalSetExcelItem1(std::vector<ExcelItem> items);
    void signalSetExcelItem2(std::vector<ExcelItem> items);
    void signalSetExcelItem3(std::vector<ExcelItem> items);
    void signalSetExcelItem4(std::vector<ExcelItem> items);
    void signalSetExcelItem5(std::vector<ExcelItem> items);
    void signalSetExcelItem6(std::vector<ExcelItem> items);
    void signalSetExcelItem7(std::vector<ExcelItem> items);
    void signalSetExcelItem8(std::vector<ExcelItem> items);
    void signalSetExcelItem9(std::vector<ExcelItem> items);
    void signalSetExcelItem10(std::vector<ExcelItem> items);
    void signalSetExcelItem11(std::vector<ExcelItem> items);
    void signalSetExcelItem12(std::vector<ExcelItem> items);
    void signalSetExcelItem13(std::vector<ExcelItem> items);
    void signalSetExcelItem14(std::vector<ExcelItem> items);
    void signalSetExcelItem15(std::vector<ExcelItem> items);
    void signalSetExcelItem16(std::vector<ExcelItem> items);
    void signalReceiveSerial(const QString &);
    void signalGetKB(float, float);
    void signalGetInfo(int, float, int);
    void signalSendTestResult1(QJsonObject);
    void signalSendTestResult2(QJsonObject);
    void signalSendTestResult3(QJsonObject);
    void signalSendTestResult4(QJsonObject);
    void signalSendTestResult5(QJsonObject);
    void signalSendTestResult6(QJsonObject);
    void signalSendTestResult7(QJsonObject);
    void signalSendTestResult8(QJsonObject);
    void signalSendTestResult9(QJsonObject);
    void signalSendTestResult10(QJsonObject);
    void signalSendTestResult11(QJsonObject);
    void signalSendTestResult12(QJsonObject);
    void signalSendTestResult13(QJsonObject);
    void signalSendTestResult14(QJsonObject);
    void signalSendTestResult15(QJsonObject);
    void signalSendTestResult16(QJsonObject);
    void signalEEPROMFinish();
    void signalEEPROMErrorFinish();
    void signalFlashFinish();
    void signalFlashErrorFinish();
    void signalRTCFinish();
    void signalRTCErrorFinish();
    void signalIOErrorFinish();
    void signalIOFinish();
    void signalDIErrorFinish();
    void signalDOErrorFinish();
    void signalDIFinish();
    void signalDOFinish();
    void signalCANFinish();
    void signalCANErrorFinish();
    void signalSerialFinish();
    void signalSerialErrorFinish();
    void signalHALLCurrentFinish();
    void signalHALLCurrentErrorFinish();
    void signalBatteryVoltageFinish();
    void signalBatteryVoltageErrorFinish();
    void signalSupplyVoltageFinish();
    void signalSupplyVoltageErrorFinish();
    void signalSystemTemperatureFinish();
    void signalSystemTemperatureErrorFinish();
    void signalInsulationResistanceFinish();
    void signalInsulationResistanceErrorFinish();
    void signalPowerFinish();
    void signalPowerErrorFinish();
    void signalHALLSignalFinish();
    void signalHALLSignalErrorFinish();
    void signalTemperatureFinish();
    void signalTemperatureErrorFinish();
    void signalFinishSet1();
    void signalFinishSet2();
    void signalFinishSet3();
    void signalFinishSet4();
    void signalFinishSet5();
    void signalFinishSet6();
    void signalFinishSet7();
    void signalFinishSet8();
    void signalFinishSet9();
    void signalFinishSet10();
    void signalFinishSet11();
    void signalFinishSet12();
    void signalFinishSet13();
    void signalFinishSet14();
    void signalFinishSet15();
    void signalFinishSet16();
    void signalFinishSet21();
    void signalFinishSet22();
    void signalFinishSet23();
    void signalFinishSet24();
    void signalFinishSet25();
    void signalFinishSet26();
    void signalFinishSet27();
    void signalFinishSet28();
    void signalFinishSet29();
    void signalFinishSet210();
    void signalFinishSet211();
    void signalFinishSet212();
    void signalFinishSet213();
    void signalFinishSet214();
    void signalFinishSet215();
    void signalFinishSet216();
    void signalSetModFail();
    void signalSendData(QByteArray);
    void signalReceiveSerial1(QString);
    void signalReceiveSerial2(QString);
    void signalReceiveSerial3(QString);
    void signalReceiveSerial4(QString);
    void signalReceiveSerial5(QString);
    void signalReceiveSerial6(QString);
    void signalReceiveSerial7(QString);
    void signalReceiveSerial8(QString);
    void signalReceiveSerial9(QString);
    void signalReceiveSerial10(QString);
    void signalReceiveSerial11(QString);
    void signalReceiveSerial12(QString);
    void signalReceiveSerial13(QString);
    void signalReceiveSerial14(QString);
    void signalReceiveSerial15(QString);
    void signalReceiveSerial16(QString);
    void signalSetSoft1(QString);
    void signalSetSoft2(QString);
    void signalSetSoft3(QString);
    void signalSetSoft4(QString);
    void signalSetSoft5(QString);
    void signalSetSoft6(QString);
    void signalSetSoft7(QString);
    void signalSetSoft8(QString);
    void signalSetSoft9(QString);
    void signalSetSoft10(QString);
    void signalSetSoft11(QString);
    void signalSetSoft12(QString);
    void signalSetSoft13(QString);
    void signalSetSoft14(QString);
    void signalSetSoft15(QString);
    void signalSetSoft16(QString);
    void signalSetHard1(QString);
    void signalSetHard2(QString);
    void signalSetHard3(QString);
    void signalSetHard4(QString);
    void signalSetHard5(QString);
    void signalSetHard6(QString);
    void signalSetHard7(QString);
    void signalSetHard8(QString);
    void signalSetHard9(QString);
    void signalSetHard10(QString);
    void signalSetHard11(QString);
    void signalSetHard12(QString);
    void signalSetHard13(QString);
    void signalSetHard14(QString);
    void signalSetHard15(QString);
    void signalSetHard16(QString);
    void signalReceiveData(VCI_CAN_OBJ);
    void signalReceiveData2(VCI_CAN_OBJ);
    void signalReceiveData(CAN_OBJ);
    void signalReceiveData2(CAN_OBJ);
    void signalSerialError1();
    void signalSerialError2();
    void signalSerialError3();
    void signalSerialError4();
    void signalSerialError5();
    void signalSerialError6();
    void signalSerialError7();
    void signalSerialError8();
    void signalSerialError9();
    void signalSerialError10();
    void signalSerialError11();
    void signalSerialError12();
    void signalSerialError13();
    void signalSerialError14();
    void signalSerialError15();
    void signalSerialError16();
    void signalStartTest1();
    void signalStartTest2();
    void signalStartTest3();
    void signalStartTest4();
    void signalStartTest5();
    void signalStartTest6();
    void signalStartTest7();
    void signalStartTest8();
    void signalStartTest9();
    void signalStartTest10();
    void signalStartTest11();
    void signalStartTest12();
    void signalStartTest13();
    void signalStartTest14();
    void signalStartTest15();
    void signalStartTest16();
    void signalSetSerial1(QString);
    void signalSetSerial2(QString);
    void signalSetSerial3(QString);
    void signalSetSerial4(QString);
    void signalSetSerial5(QString);
    void signalSetSerial6(QString);
    void signalSetSerial7(QString);
    void signalSetSerial8(QString);
    void signalSetSerial9(QString);
    void signalSetSerial10(QString);
    void signalSetSerial11(QString);
    void signalSetSerial12(QString);
    void signalSetSerial13(QString);
    void signalSetSerial14(QString);
    void signalSetSerial15(QString);
    void signalSetSerial16(QString);
    void signalSetMAC1(QString);
    void signalSetMAC2(QString);
    void signalSetMAC3(QString);
    void signalSetMAC4(QString);
    void signalSetMAC5(QString);
    void signalSetMAC6(QString);
    void signalSetMAC7(QString);
    void signalSetMAC8(QString);
    void signalSetMAC9(QString);
    void signalSetMAC10(QString);
    void signalSetMAC11(QString);
    void signalSetMAC12(QString);
    void signalSetMAC13(QString);
    void signalSetMAC14(QString);
    void signalSetMAC15(QString);
    void signalSetMAC16(QString);
    void signalSetTestMod1();
    void signalSetTestMod2();
    void signalSetTestMod3();
    void signalSetTestMod4();
    void signalSetTestMod5();
    void signalSetTestMod6();
    void signalSetTestMod7();
    void signalSetTestMod8();
    void signalSetTestMod9();
    void signalSetTestMod10();
    void signalSetTestMod11();
    void signalSetTestMod12();
    void signalSetTestMod13();
    void signalSetTestMod14();
    void signalSetTestMod15();
    void signalSetTestMod16();

    void signalSetModFail1();
    void signalSetModFail2();
    void signalSetModFail3();
    void signalSetModFail4();
    void signalSetModFail5();
    void signalSetModFail6();
    void signalSetModFail7();
    void signalSetModFail8();
    void signalSetModFail9();
    void signalSetModFail10();
    void signalSetModFail11();
    void signalSetModFail12();
    void signalSetModFail13();
    void signalSetModFail14();
    void signalSetModFail15();
    void signalSetModFail16();

    void signalTimeout1();
    void signalTimeout2();
    void signalTimeout3();
    void signalTimeout4();
    void signalTimeout5();
    void signalTimeout6();
    void signalTimeout7();
    void signalTimeout8();
    void signalTimeout9();
    void signalTimeout10();
    void signalTimeout11();
    void signalTimeout12();
    void signalTimeout13();
    void signalTimeout14();
    void signalTimeout15();
    void signalTimeout16();

    void signalSetModFail21();
    void signalSetModFail22();
    void signalSetModFail23();
    void signalSetModFail24();
    void signalSetModFail25();
    void signalSetModFail26();
    void signalSetModFail27();
    void signalSetModFail28();
    void signalSetModFail29();
    void signalSetModFail210();
    void signalSetModFail211();
    void signalSetModFail212();
    void signalSetModFail213();
    void signalSetModFail214();
    void signalSetModFail215();
    void signalSetModFail216();

    void signalIfCanUpdate1To4(bool);
    void signalIfCanUpdate5To8(bool);
    void signalIfCanUpdate9To12(bool);
    void signalIfCanUpdate13To16(bool);
};

#endif // CANBUSCONTROL_H
