#ifndef MAINCONTROL_H
#define MAINCONTROL_H
#include <QObject>
#include <QStateMachine>
#include <QJsonObject>
#include "excelcontrol.h"
#include "model/networkapi.h"
#include "model/jsonmerge.h"

class CanBusControl;
class ExcelControl;
class MainWindow;
class ChooseDeviceDialog;
class ChooseTypeDialog;
class MainControl : public QObject
{
    Q_OBJECT
public:
    enum TestItemIdentify
    {
        StateStartTest                     = 1,
        StateTestSetBatteryVoltage         = 2,
        StateTestSetHALLCurrent            = 3,
        StateTestSetRTC                    = 4,
        StateTestSetMAC                    = 5,
        StateTestSetSerial                 = 6,
        StateTestZDResistance              = 7,
        StateTestBatteryVoltage            = 8,
        StateTestHALLCurrent               = 9,
        StateTestSupplyVoltage             = 10,
        StateTestPower                     = 11,
        StateTestHALLSignal                = 12,
        StateTestTemperature               = 13,
        StateTestEncodeInterface           = 14,
        StateTestDO                        = 15,
        StateTestDIAndSLP                  = 16,
        StateTestSerialCommunication       = 17,
        StateTestCANCommunication          = 18,
        StateTestEEPROM                    = 19,
        StateTestFlash                     = 20,
        StateTestRTC                       = 21,
        StateTestSystemTemperature         = 22,
        StateTestReadMAC                   = 23,
        StateTestReadSerial                = 24,
        StateTestInternet                  = 25,
        StateTestInsulationResistance      = 26,
        StateTestSoftWareVersion           = 27,
        StateTestHardWareVersion           = 28,
        StateTestSPI                       = 29,
        StateTestKB                        = 30,
        StateFinishTest                    = 31,
        StateExitTest                      = 32,
        StateUnknownType                   = 99
    };
    Q_ENUM(TestItemIdentify)
    MainControl();
    ~MainControl();
    void layoutUI();
    void connectFunc();
    void initializeStateMachine();

private:
    bool updateTestState1();
    bool updateTestState2();
    bool updateTestState3();
    bool updateTestState4();
    bool updateTestState5();
    bool updateTestState6();
    bool updateTestState7();
    bool updateTestState8();
    bool updateTestState9();
    bool updateTestState10();
    bool updateTestState11();
    bool updateTestState12();
    bool updateTestState13();
    bool updateTestState14();
    bool updateTestState15();
    bool updateTestState16();
    QString findRenderSignal1(QState* state);
    QString findRenderSignal1(const TestItemIdentify& type);
    QState* findState1(const QString&) const;
    QState* findState1(const TestItemIdentify&) const;
    void createTestStateLogic1(const QVector<QState*>& tempVecState);
    QString findRenderSignal2(QState* state);
    QString findRenderSignal2(const TestItemIdentify& type);
    QState* findState2(const QString&) const;
    QState* findState2(const TestItemIdentify&) const;
    QString findRenderSignal3(QState* state);
    QString findRenderSignal3(const TestItemIdentify& type);
    QState* findState3(const QString&) const;
    QState* findState3(const TestItemIdentify&) const;
    void createTestStateLogic3(const QVector<QState*>& tempVecState);
    void createTestStateLogic2(const QVector<QState*>& tempVecState);
    QString findRenderSignal4(QState* state);
    QString findRenderSignal4(const TestItemIdentify& type);
    QState* findState4(const QString&) const;
    QState* findState4(const TestItemIdentify&) const;
    void createTestStateLogic4(const QVector<QState*>& tempVecState);
    QString findRenderSignal5(QState* state);
    QString findRenderSignal5(const TestItemIdentify& type);
    QState* findState5(const QString&) const;
    QState* findState5(const TestItemIdentify&) const;
    void createTestStateLogic5(const QVector<QState*>& tempVecState);
    QString findRenderSignal6(QState* state);
    QString findRenderSignal6(const TestItemIdentify& type);
    QState* findState6(const QString&) const;
    QState* findState6(const TestItemIdentify&) const;
    void createTestStateLogic6(const QVector<QState*>& tempVecState);
    QString findRenderSignal7(QState* state);
    QString findRenderSignal7(const TestItemIdentify& type);
    QState* findState7(const QString&) const;
    QState* findState7(const TestItemIdentify&) const;
    void createTestStateLogic7(const QVector<QState*>& tempVecState);
    QString findRenderSignal8(QState* state);
    QString findRenderSignal8(const TestItemIdentify& type);
    QState* findState8(const QString&) const;
    QState* findState8(const TestItemIdentify&) const;
    void createTestStateLogic8(const QVector<QState*>& tempVecState);
    QString findRenderSignal9(QState* state);
    QString findRenderSignal9(const TestItemIdentify& type);
    QState* findState9(const QString&) const;
    QState* findState9(const TestItemIdentify&) const;
    void createTestStateLogic9(const QVector<QState*>& tempVecState);
    QString findRenderSignal10(QState* state);
    QString findRenderSignal10(const TestItemIdentify& type);
    QState* findState10(const QString&) const;
    QState* findState10(const TestItemIdentify&) const;
    void createTestStateLogic10(const QVector<QState*>& tempVecState);
    QString findRenderSignal11(QState* state);
    QString findRenderSignal11(const TestItemIdentify& type);
    QState* findState11(const QString&) const;
    QState* findState11(const TestItemIdentify&) const;
    void createTestStateLogic11(const QVector<QState*>& tempVecState);
    QString findRenderSignal12(QState* state);
    QString findRenderSignal12(const TestItemIdentify& type);
    QState* findState12(const QString&) const;
    QState* findState12(const TestItemIdentify&) const;
    void createTestStateLogic12(const QVector<QState*>& tempVecState);
    QString findRenderSignal13(QState* state);
    QString findRenderSignal13(const TestItemIdentify& type);
    QState* findState13(const QString&) const;
    QState* findState13(const TestItemIdentify&) const;
    void createTestStateLogic13(const QVector<QState*>& tempVecState);
    QString findRenderSignal14(QState* state);
    QString findRenderSignal14(const TestItemIdentify& type);
    QState* findState14(const QString&) const;
    QState* findState14(const TestItemIdentify&) const;
    void createTestStateLogic14(const QVector<QState*>& tempVecState);
    QString findRenderSignal15(QState* state);
    QString findRenderSignal15(const TestItemIdentify& type);
    QState* findState15(const QString&) const;
    QState* findState15(const TestItemIdentify&) const;
    void createTestStateLogic15(const QVector<QState*>& tempVecState);
    QString findRenderSignal16(QState* state);
    QString findRenderSignal16(const TestItemIdentify& type);
    QState* findState16(const QString&) const;
    QState* findState16(const TestItemIdentify&) const;
    void createTestStateLogic16(const QVector<QState*>& tempVecState);
    void emitSignals1();
    void emitSignals2();
    void emitSignals3();
    void emitSignals4();
    void emitSignals5();
    void emitSignals6();
    void emitSignals7();
    void emitSignals8();
    void emitSignals9();
    void emitSignals10();
    void emitSignals11();
    void emitSignals12();
    void emitSignals13();
    void emitSignals14();
    void emitSignals15();
    void emitSignals16();

private:
    CanBusControl *canbusControl;
    ExcelControl *excelControl1 = NULL;
    ExcelControl *excelControl2 = NULL;
    ExcelControl *excelControl3 = NULL;
    ExcelControl *excelControl4 = NULL;
    ExcelControl *excelControl5 = NULL;
    ExcelControl *excelControl6 = NULL;
    ExcelControl *excelControl7 = NULL;
    ExcelControl *excelControl8 = NULL;
    ExcelControl *excelControl9 = NULL;
    ExcelControl *excelControl10 = NULL;
    ExcelControl *excelControl11 = NULL;
    ExcelControl *excelControl12 = NULL;
    ExcelControl *excelControl13 = NULL;
    ExcelControl *excelControl14 = NULL;
    ExcelControl *excelControl15 = NULL;
    ExcelControl *excelControl16 = NULL;
    MainWindow *mainWindow;
    ChooseDeviceDialog *chooseDeviceWidget;
    TestItemIdentify currentTest1;
    TestItemIdentify currentTest2;
    TestItemIdentify currentTest3;
    TestItemIdentify currentTest4;
    TestItemIdentify currentTest5;
    TestItemIdentify currentTest6;
    TestItemIdentify currentTest7;
    TestItemIdentify currentTest8;
    TestItemIdentify currentTest9;
    TestItemIdentify currentTest10;
    TestItemIdentify currentTest11;
    TestItemIdentify currentTest12;
    TestItemIdentify currentTest13;
    TestItemIdentify currentTest14;
    TestItemIdentify currentTest15;
    TestItemIdentify currentTest16;
    QStateMachine* m_stateMachine1;
    QStateMachine* m_stateMachine2;
    QStateMachine* m_stateMachine3;
    QStateMachine* m_stateMachine4;
    QStateMachine* m_stateMachine5;
    QStateMachine* m_stateMachine6;
    QStateMachine* m_stateMachine7;
    QStateMachine* m_stateMachine8;
    QStateMachine* m_stateMachine9;
    QStateMachine* m_stateMachine10;
    QStateMachine* m_stateMachine11;
    QStateMachine* m_stateMachine12;
    QStateMachine* m_stateMachine13;
    QStateMachine* m_stateMachine14;
    QStateMachine* m_stateMachine15;
    QStateMachine* m_stateMachine16;
    TestItemIdentify lastTest1;
    TestItemIdentify lastTest2;
    TestItemIdentify lastTest3;
    TestItemIdentify lastTest4;
    TestItemIdentify lastTest5;
    TestItemIdentify lastTest6;
    TestItemIdentify lastTest7;
    TestItemIdentify lastTest8;
    TestItemIdentify lastTest9;
    TestItemIdentify lastTest10;
    TestItemIdentify lastTest11;
    TestItemIdentify lastTest12;
    TestItemIdentify lastTest13;
    TestItemIdentify lastTest14;
    TestItemIdentify lastTest15;
    TestItemIdentify lastTest16;
    bool ifContinue;
    QString ipAddress;
    ChooseTypeDialog *typeDialog;
    QThread *canbusThread;
    int m_type1 = 0;
    int m_type2 = 0;
    int m_type3 = 0;
    int m_type4 = 0;
    int m_type5 = 0;
    int m_type6 = 0;
    int m_type7 = 0;
    int m_type8 = 0;
    int m_type9 = 0;
    int m_type10 = 0;
    int m_type11 = 0;
    int m_type12 = 0;
    int m_type13 = 0;
    int m_type14 = 0;
    int m_type15 = 0;
    int m_type16 = 0;
    QString m_serial1;
    QString m_serial2;
    QString m_serial3;
    QString m_serial4;
    QString m_serial5;
    QString m_serial6;
    QString m_serial7;
    QString m_serial8;
    QString m_serial9;
    QString m_serial10;
    QString m_serial11;
    QString m_serial12;
    QString m_serial13;
    QString m_serial14;
    QString m_serial15;
    QString m_serial16;
    bool testResult1 = true;
    bool testResult2 = true;
    bool testResult3 = true;
    bool testResult4 = true;
    bool testResult5 = true;
    bool testResult6 = true;
    bool testResult7 = true;
    bool testResult8 = true;
    bool testResult9 = true;
    bool testResult10 = true;
    bool testResult11 = true;
    bool testResult12 = true;
    bool testResult13 = true;
    bool testResult14 = true;
    bool testResult15 = true;
    bool testResult16 = true;
    JsonMerge *merge;
    NetWorkAPI *api;
    bool m_mod = false;
    QJsonObject result1;
    QJsonObject result2;
    QJsonObject result3;
    QJsonObject result4;
    QJsonObject result5;
    QJsonObject result6;
    QJsonObject result7;
    QJsonObject result8;
    QJsonObject result9;
    QJsonObject result10;
    QJsonObject result11;
    QJsonObject result12;
    QJsonObject result13;
    QJsonObject result14;
    QJsonObject result15;
    QJsonObject result16;
    bool if_test1 = true;
    bool if_test2 = true;
    bool if_test3 = true;
    bool if_test4 = true;
    bool if_test5 = true;
    bool if_test6 = true;
    bool if_test7 = true;
    bool if_test8 = true;
    bool if_test9 = true;
    bool if_test10 = true;
    bool if_test11 = true;
    bool if_test12 = true;
    bool if_test13 = true;
    bool if_test14 = true;
    bool if_test15 = true;
    bool if_test16 = true;

public slots:
    void slotOpenConnPage();
    void slotStartCanBus(int type, int id, int pass, int port);
    void slotChooseZLG();
    void slotChooseGC();
    void slotCreateExcel1(std::vector<ExcelItem> items);
    void slotCreateExcel2(std::vector<ExcelItem> items);
    void slotCreateExcel3(std::vector<ExcelItem> items);
    void slotCreateExcel4(std::vector<ExcelItem> items);
    void slotCreateExcel5(std::vector<ExcelItem> items);
    void slotCreateExcel6(std::vector<ExcelItem> items);
    void slotCreateExcel7(std::vector<ExcelItem> items);
    void slotCreateExcel8(std::vector<ExcelItem> items);
    void slotCreateExcel9(std::vector<ExcelItem> items);
    void slotCreateExcel10(std::vector<ExcelItem> items);
    void slotCreateExcel11(std::vector<ExcelItem> items);
    void slotCreateExcel12(std::vector<ExcelItem> items);
    void slotCreateExcel13(std::vector<ExcelItem> items);
    void slotCreateExcel14(std::vector<ExcelItem> items);
    void slotCreateExcel15(std::vector<ExcelItem> items);
    void slotCreateExcel16(std::vector<ExcelItem> items);
    void slotCloseCANPort();
    void slotEnterTestState1();
    void slotExitTestState1();
    void slotEnterTestState2();
    void slotExitTestState2();
    void slotEnterTestState3();
    void slotExitTestState3();
    void slotEnterTestState4();
    void slotExitTestState4();
    void slotEnterTestState5();
    void slotExitTestState5();
    void slotEnterTestState6();
    void slotExitTestState6();
    void slotEnterTestState7();
    void slotExitTestState7();
    void slotEnterTestState8();
    void slotExitTestState8();
    void slotEnterTestState9();
    void slotExitTestState9();
    void slotEnterTestState10();
    void slotExitTestState10();
    void slotEnterTestState11();
    void slotExitTestState11();
    void slotEnterTestState12();
    void slotExitTestState12();
    void slotEnterTestState13();
    void slotExitTestState13();
    void slotEnterTestState14();
    void slotExitTestState14();
    void slotEnterTestState15();
    void slotExitTestState15();
    void slotEnterTestState16();
    void slotExitTestState16();
    void slotTryUpadateStates1(int status);
    void slotTryUpadateStates2(int status);
    void slotTryUpadateStates3(int status);
    void slotTryUpadateStates4(int status);
    void slotTryUpadateStates5(int status);
    void slotTryUpadateStates6(int status);
    void slotTryUpadateStates7(int status);
    void slotTryUpadateStates8(int status);
    void slotTryUpadateStates9(int status);
    void slotTryUpadateStates10(int status);
    void slotTryUpadateStates11(int status);
    void slotTryUpadateStates12(int status);
    void slotTryUpadateStates13(int status);
    void slotTryUpadateStates14(int status);
    void slotTryUpadateStates15(int status);
    void slotTryUpadateStates16(int status);
    void slotStartTest1();
    void slotStartTest2();
    void slotStartTest3();
    void slotStartTest4();
    void slotStartTest5();
    void slotStartTest6();
    void slotStartTest7();
    void slotStartTest8();
    void slotStartTest9();
    void slotStartTest10();
    void slotStartTest11();
    void slotStartTest12();
    void slotStartTest13();
    void slotStartTest14();
    void slotStartTest15();
    void slotStartTest16();
    void slotErrorFinish1();
    void slotErrorFinish2();
    void slotErrorFinish3();
    void slotErrorFinish4();
    void slotErrorFinish5();
    void slotErrorFinish6();
    void slotErrorFinish7();
    void slotErrorFinish8();
    void slotErrorFinish9();
    void slotErrorFinish10();
    void slotErrorFinish11();
    void slotErrorFinish12();
    void slotErrorFinish13();
    void slotErrorFinish14();
    void slotErrorFinish15();
    void slotErrorFinish16();
    void slotChangeContinue(int s);
    void slotStartMainWindow(bool mod, int type1, int type2, int type3, int type4, int type5
                             , int type6, int type7, int type8, int type9, int type10
                             , int type11, int type12, int type13, int type14, int type15, int type16);
    void slotQuit();
    void slotSetSerial(const QString &serial);
    void slotTestResult1(bool result);
    void slotTestResult2(bool result);
    void slotTestResult3(bool result);
    void slotTestResult4(bool result);
    void slotTestResult5(bool result);
    void slotTestResult6(bool result);
    void slotTestResult7(bool result);
    void slotTestResult8(bool result);
    void slotTestResult9(bool result);
    void slotTestResult10(bool result);
    void slotTestResult11(bool result);
    void slotTestResult12(bool result);
    void slotTestResult13(bool result);
    void slotTestResult14(bool result);
    void slotTestResult15(bool result);
    void slotTestResult16(bool result);
    void slotGetSerialStatus(std::vector<ErrorDetial> fails);
    void slotFinishSet1();
    void slotFinishSet2();
    void slotFinishSet3();
    void slotFinishSet4();
    void slotFinishSet5();
    void slotFinishSet6();
    void slotFinishSet7();
    void slotFinishSet8();
    void slotFinishSet9();
    void slotFinishSet10();
    void slotFinishSet11();
    void slotFinishSet12();
    void slotFinishSet13();
    void slotFinishSet14();
    void slotFinishSet15();
    void slotFinishSet16();
    void slotFinishSet21();
    void slotFinishSet22();
    void slotFinishSet23();
    void slotFinishSet24();
    void slotFinishSet25();
    void slotFinishSet26();
    void slotFinishSet27();
    void slotFinishSet28();
    void slotFinishSet29();
    void slotFinishSet210();
    void slotFinishSet211();
    void slotFinishSet212();
    void slotFinishSet213();
    void slotFinishSet214();
    void slotFinishSet215();
    void slotFinishSet216();
    void slotReceiveSerial1(QString serial);
    void slotReceiveSerial2(QString serial);
    void slotReceiveSerial3(QString serial);
    void slotReceiveSerial4(QString serial);
    void slotReceiveSerial5(QString serial);
    void slotReceiveSerial6(QString serial);
    void slotReceiveSerial7(QString serial);
    void slotReceiveSerial8(QString serial);
    void slotReceiveSerial9(QString serial);
    void slotReceiveSerial10(QString serial);
    void slotReceiveSerial11(QString serial);
    void slotReceiveSerial12(QString serial);
    void slotReceiveSerial13(QString serial);
    void slotReceiveSerial14(QString serial);
    void slotReceiveSerial15(QString serial);
    void slotReceiveSerial16(QString serial);
    
    void slotSetJson1(QJsonObject data);
    void slotSetJson2(QJsonObject data);
    void slotSetJson3(QJsonObject data);
    void slotSetJson4(QJsonObject data);
    void slotSetJson5(QJsonObject data);
    void slotSetJson6(QJsonObject data);
    void slotSetJson7(QJsonObject data);
    void slotSetJson8(QJsonObject data);
    void slotSetJson9(QJsonObject data);
    void slotSetJson10(QJsonObject data);
    void slotSetJson11(QJsonObject data);
    void slotSetJson12(QJsonObject data);
    void slotSetJson13(QJsonObject data);
    void slotSetJson14(QJsonObject data);
    void slotSetJson15(QJsonObject data);
    void slotSetJson16(QJsonObject data);
    
    void slotAddJson1(QJsonObject data);
    void slotAddJson2(QJsonObject data);
    void slotAddJson3(QJsonObject data);
    void slotAddJson4(QJsonObject data);
    void slotAddJson5(QJsonObject data);
    void slotAddJson6(QJsonObject data);
    void slotAddJson7(QJsonObject data);
    void slotAddJson8(QJsonObject data);
    void slotAddJson9(QJsonObject data);
    void slotAddJson10(QJsonObject data);
    void slotAddJson11(QJsonObject data);
    void slotAddJson12(QJsonObject data);
    void slotAddJson13(QJsonObject data);
    void slotAddJson14(QJsonObject data);
    void slotAddJson15(QJsonObject data);
    void slotAddJson16(QJsonObject data);
    
    void slotSendJson1();
    void slotSendJson2();
    void slotSendJson3();
    void slotSendJson4();
    void slotSendJson5();
    void slotSendJson6();
    void slotSendJson7();
    void slotSendJson8();
    void slotSendJson9();
    void slotSendJson10();
    void slotSendJson11();
    void slotSendJson12();
    void slotSendJson13();
    void slotSendJson14();
    void slotSendJson15();
    void slotSendJson16();

    void slotSingleFail1();
    void slotSingleFail2();
    void slotSingleFail3();
    void slotSingleFail4();
    void slotSingleFail5();
    void slotSingleFail6();
    void slotSingleFail7();
    void slotSingleFail8();
    void slotSingleFail9();
    void slotSingleFail10();
    void slotSingleFail11();
    void slotSingleFail12();
    void slotSingleFail13();
    void slotSingleFail14();
    void slotSingleFail15();
    void slotSingleFail16();

    void slotSingleFail21();
    void slotSingleFail22();
    void slotSingleFail23();
    void slotSingleFail24();
    void slotSingleFail25();
    void slotSingleFail26();
    void slotSingleFail27();
    void slotSingleFail28();
    void slotSingleFail29();
    void slotSingleFail210();
    void slotSingleFail211();
    void slotSingleFail212();
    void slotSingleFail213();
    void slotSingleFail214();
    void slotSingleFail215();
    void slotSingleFail216();

    void slotTimeout1();
    void slotTimeout2();
    void slotTimeout3();
    void slotTimeout4();
    void slotTimeout5();
    void slotTimeout6();
    void slotTimeout7();
    void slotTimeout8();
    void slotTimeout9();
    void slotTimeout10();
    void slotTimeout11();
    void slotTimeout12();
    void slotTimeout13();
    void slotTimeout14();
    void slotTimeout15();
    void slotTimeout16();

signals:
    void signalChangeOpenDeviceStatus();
    void signalEnterStateUnknownType1();
    void signalEnterStateUnknownType2();
    void signalEnterStateUnknownType3();
    void signalEnterStateUnknownType4();
    void signalEnterStateUnknownType5();
    void signalEnterStateUnknownType6();
    void signalEnterStateUnknownType7();
    void signalEnterStateUnknownType8();
    void signalEnterStateUnknownType9();
    void signalEnterStateUnknownType10();
    void signalEnterStateUnknownType11();
    void signalEnterStateUnknownType12();
    void signalEnterStateUnknownType13();
    void signalEnterStateUnknownType14();
    void signalEnterStateUnknownType15();
    void signalEnterStateUnknownType16();
    void signalEnterStateStartTest1();
    void signalEnterStateTestSetBatteryVoltage1();
    void signalEnterStateTestSetHALLCurrent1();
    void signalEnterStateTestSetRTC1();
    void signalEnterStateTestSetMAC1();
    void signalEnterStateTestSetSerial1();
    void signalEnterStateTestZDResistance1();
    void signalEnterStateTestBatteryVoltage1();
    void signalEnterStateTestHALLCurrent1();
    void signalEnterStateTestSupplyVoltage1();
    void signalEnterStateTestPower1();
    void signalEnterStateTestHALLSignal1();
    void signalEnterStateTestTemperature1();
    void signalEnterStateTestEncodeInterface1();
    void signalEnterStateTestDO1();
    void signalEnterStateTestDIAndSLP1();
    void signalEnterStateTestSerialCommunication1();
    void signalEnterStateTestCANCommunication1();
    void signalEnterStateTestEEPROM1();
    void signalEnterStateTestFlash1();
    void signalEnterStateTestRTC1();
    void signalEnterStateTestSystemTemperature1();
    void signalEnterStateTestReadMAC1();
    void signalEnterStateTestReadSerial1();
    void signalEnterStateTestInternet1();
    void signalEnterStateTestInsulationResistance1();
    void signalEnterStateTestSoftWareVersion1();
    void signalEnterStateTestHardWareVersion1();
    void signalEnterStateTestSPI1();
    void signalEnterStateTestKB1();
    void signalEnterStateFinishTest1();
    void signalEnterStateExitTest1();

    void signalEnterStateStartTest2();
    void signalEnterStateTestSetBatteryVoltage2();
    void signalEnterStateTestSetHALLCurrent2();
    void signalEnterStateTestSetRTC2();
    void signalEnterStateTestSetMAC2();
    void signalEnterStateTestSetSerial2();
    void signalEnterStateTestZDResistance2();
    void signalEnterStateTestBatteryVoltage2();
    void signalEnterStateTestHALLCurrent2();
    void signalEnterStateTestSupplyVoltage2();
    void signalEnterStateTestPower2();
    void signalEnterStateTestHALLSignal2();
    void signalEnterStateTestTemperature2();
    void signalEnterStateTestEncodeInterface2();
    void signalEnterStateTestDO2();
    void signalEnterStateTestDIAndSLP2();
    void signalEnterStateTestSerialCommunication2();
    void signalEnterStateTestCANCommunication2();
    void signalEnterStateTestEEPROM2();
    void signalEnterStateTestFlash2();
    void signalEnterStateTestRTC2();
    void signalEnterStateTestSystemTemperature2();
    void signalEnterStateTestReadMAC2();
    void signalEnterStateTestReadSerial2();
    void signalEnterStateTestInternet2();
    void signalEnterStateTestInsulationResistance2();
    void signalEnterStateTestSoftWareVersion2();
    void signalEnterStateTestHardWareVersion2();
    void signalEnterStateTestSPI2();
    void signalEnterStateTestKB2();
    void signalEnterStateFinishTest2();
    void signalEnterStateExitTest2();

    void signalEnterStateStartTest3();
    void signalEnterStateTestSetBatteryVoltage3();
    void signalEnterStateTestSetHALLCurrent3();
    void signalEnterStateTestSetRTC3();
    void signalEnterStateTestSetMAC3();
    void signalEnterStateTestSetSerial3();
    void signalEnterStateTestZDResistance3();
    void signalEnterStateTestBatteryVoltage3();
    void signalEnterStateTestHALLCurrent3();
    void signalEnterStateTestSupplyVoltage3();
    void signalEnterStateTestPower3();
    void signalEnterStateTestHALLSignal3();
    void signalEnterStateTestTemperature3();
    void signalEnterStateTestEncodeInterface3();
    void signalEnterStateTestDO3();
    void signalEnterStateTestDIAndSLP3();
    void signalEnterStateTestSerialCommunication3();
    void signalEnterStateTestCANCommunication3();
    void signalEnterStateTestEEPROM3();
    void signalEnterStateTestFlash3();
    void signalEnterStateTestRTC3();
    void signalEnterStateTestSystemTemperature3();
    void signalEnterStateTestReadMAC3();
    void signalEnterStateTestReadSerial3();
    void signalEnterStateTestInternet3();
    void signalEnterStateTestInsulationResistance3();
    void signalEnterStateTestSoftWareVersion3();
    void signalEnterStateTestHardWareVersion3();
    void signalEnterStateTestSPI3();
    void signalEnterStateTestKB3();
    void signalEnterStateFinishTest3();
    void signalEnterStateExitTest3();

    void signalEnterStateStartTest4();
    void signalEnterStateTestSetBatteryVoltage4();
    void signalEnterStateTestSetHALLCurrent4();
    void signalEnterStateTestSetRTC4();
    void signalEnterStateTestSetMAC4();
    void signalEnterStateTestSetSerial4();
    void signalEnterStateTestZDResistance4();
    void signalEnterStateTestBatteryVoltage4();
    void signalEnterStateTestHALLCurrent4();
    void signalEnterStateTestSupplyVoltage4();
    void signalEnterStateTestPower4();
    void signalEnterStateTestHALLSignal4();
    void signalEnterStateTestTemperature4();
    void signalEnterStateTestEncodeInterface4();
    void signalEnterStateTestDO4();
    void signalEnterStateTestDIAndSLP4();
    void signalEnterStateTestSerialCommunication4();
    void signalEnterStateTestCANCommunication4();
    void signalEnterStateTestEEPROM4();
    void signalEnterStateTestFlash4();
    void signalEnterStateTestRTC4();
    void signalEnterStateTestSystemTemperature4();
    void signalEnterStateTestReadMAC4();
    void signalEnterStateTestReadSerial4();
    void signalEnterStateTestInternet4();
    void signalEnterStateTestInsulationResistance4();
    void signalEnterStateTestSoftWareVersion4();
    void signalEnterStateTestHardWareVersion4();
    void signalEnterStateTestSPI4();
    void signalEnterStateTestKB4();
    void signalEnterStateFinishTest4();
    void signalEnterStateExitTest4();

    void signalEnterStateStartTest5();
    void signalEnterStateTestSetBatteryVoltage5();
    void signalEnterStateTestSetHALLCurrent5();
    void signalEnterStateTestSetRTC5();
    void signalEnterStateTestSetMAC5();
    void signalEnterStateTestSetSerial5();
    void signalEnterStateTestZDResistance5();
    void signalEnterStateTestBatteryVoltage5();
    void signalEnterStateTestHALLCurrent5();
    void signalEnterStateTestSupplyVoltage5();
    void signalEnterStateTestPower5();
    void signalEnterStateTestHALLSignal5();
    void signalEnterStateTestTemperature5();
    void signalEnterStateTestEncodeInterface5();
    void signalEnterStateTestDO5();
    void signalEnterStateTestDIAndSLP5();
    void signalEnterStateTestSerialCommunication5();
    void signalEnterStateTestCANCommunication5();
    void signalEnterStateTestEEPROM5();
    void signalEnterStateTestFlash5();
    void signalEnterStateTestRTC5();
    void signalEnterStateTestSystemTemperature5();
    void signalEnterStateTestReadMAC5();
    void signalEnterStateTestReadSerial5();
    void signalEnterStateTestInternet5();
    void signalEnterStateTestInsulationResistance5();
    void signalEnterStateTestSoftWareVersion5();
    void signalEnterStateTestHardWareVersion5();
    void signalEnterStateTestSPI5();
    void signalEnterStateTestKB5();
    void signalEnterStateFinishTest5();
    void signalEnterStateExitTest5();

    void signalEnterStateStartTest6();
    void signalEnterStateTestSetBatteryVoltage6();
    void signalEnterStateTestSetHALLCurrent6();
    void signalEnterStateTestSetRTC6();
    void signalEnterStateTestSetMAC6();
    void signalEnterStateTestSetSerial6();
    void signalEnterStateTestZDResistance6();
    void signalEnterStateTestBatteryVoltage6();
    void signalEnterStateTestHALLCurrent6();
    void signalEnterStateTestSupplyVoltage6();
    void signalEnterStateTestPower6();
    void signalEnterStateTestHALLSignal6();
    void signalEnterStateTestTemperature6();
    void signalEnterStateTestEncodeInterface6();
    void signalEnterStateTestDO6();
    void signalEnterStateTestDIAndSLP6();
    void signalEnterStateTestSerialCommunication6();
    void signalEnterStateTestCANCommunication6();
    void signalEnterStateTestEEPROM6();
    void signalEnterStateTestFlash6();
    void signalEnterStateTestRTC6();
    void signalEnterStateTestSystemTemperature6();
    void signalEnterStateTestReadMAC6();
    void signalEnterStateTestReadSerial6();
    void signalEnterStateTestInternet6();
    void signalEnterStateTestInsulationResistance6();
    void signalEnterStateTestSoftWareVersion6();
    void signalEnterStateTestHardWareVersion6();
    void signalEnterStateTestSPI6();
    void signalEnterStateTestKB6();
    void signalEnterStateFinishTest6();
    void signalEnterStateExitTest6();

    void signalEnterStateStartTest7();
    void signalEnterStateTestSetBatteryVoltage7();
    void signalEnterStateTestSetHALLCurrent7();
    void signalEnterStateTestSetRTC7();
    void signalEnterStateTestSetMAC7();
    void signalEnterStateTestSetSerial7();
    void signalEnterStateTestZDResistance7();
    void signalEnterStateTestBatteryVoltage7();
    void signalEnterStateTestHALLCurrent7();
    void signalEnterStateTestSupplyVoltage7();
    void signalEnterStateTestPower7();
    void signalEnterStateTestHALLSignal7();
    void signalEnterStateTestTemperature7();
    void signalEnterStateTestEncodeInterface7();
    void signalEnterStateTestDO7();
    void signalEnterStateTestDIAndSLP7();
    void signalEnterStateTestSerialCommunication7();
    void signalEnterStateTestCANCommunication7();
    void signalEnterStateTestEEPROM7();
    void signalEnterStateTestFlash7();
    void signalEnterStateTestRTC7();
    void signalEnterStateTestSystemTemperature7();
    void signalEnterStateTestReadMAC7();
    void signalEnterStateTestReadSerial7();
    void signalEnterStateTestInternet7();
    void signalEnterStateTestInsulationResistance7();
    void signalEnterStateTestSoftWareVersion7();
    void signalEnterStateTestHardWareVersion7();
    void signalEnterStateTestSPI7();
    void signalEnterStateTestKB7();
    void signalEnterStateFinishTest7();
    void signalEnterStateExitTest7();

    void signalEnterStateStartTest8();
    void signalEnterStateTestSetBatteryVoltage8();
    void signalEnterStateTestSetHALLCurrent8();
    void signalEnterStateTestSetRTC8();
    void signalEnterStateTestSetMAC8();
    void signalEnterStateTestSetSerial8();
    void signalEnterStateTestZDResistance8();
    void signalEnterStateTestBatteryVoltage8();
    void signalEnterStateTestHALLCurrent8();
    void signalEnterStateTestSupplyVoltage8();
    void signalEnterStateTestPower8();
    void signalEnterStateTestHALLSignal8();
    void signalEnterStateTestTemperature8();
    void signalEnterStateTestEncodeInterface8();
    void signalEnterStateTestDO8();
    void signalEnterStateTestDIAndSLP8();
    void signalEnterStateTestSerialCommunication8();
    void signalEnterStateTestCANCommunication8();
    void signalEnterStateTestEEPROM8();
    void signalEnterStateTestFlash8();
    void signalEnterStateTestRTC8();
    void signalEnterStateTestSystemTemperature8();
    void signalEnterStateTestReadMAC8();
    void signalEnterStateTestReadSerial8();
    void signalEnterStateTestInternet8();
    void signalEnterStateTestInsulationResistance8();
    void signalEnterStateTestSoftWareVersion8();
    void signalEnterStateTestHardWareVersion8();
    void signalEnterStateTestSPI8();
    void signalEnterStateTestKB8();
    void signalEnterStateFinishTest8();
    void signalEnterStateExitTest8();

    void signalEnterStateStartTest9();
    void signalEnterStateTestSetBatteryVoltage9();
    void signalEnterStateTestSetHALLCurrent9();
    void signalEnterStateTestSetRTC9();
    void signalEnterStateTestSetMAC9();
    void signalEnterStateTestSetSerial9();
    void signalEnterStateTestZDResistance9();
    void signalEnterStateTestBatteryVoltage9();
    void signalEnterStateTestHALLCurrent9();
    void signalEnterStateTestSupplyVoltage9();
    void signalEnterStateTestPower9();
    void signalEnterStateTestHALLSignal9();
    void signalEnterStateTestTemperature9();
    void signalEnterStateTestEncodeInterface9();
    void signalEnterStateTestDO9();
    void signalEnterStateTestDIAndSLP9();
    void signalEnterStateTestSerialCommunication9();
    void signalEnterStateTestCANCommunication9();
    void signalEnterStateTestEEPROM9();
    void signalEnterStateTestFlash9();
    void signalEnterStateTestRTC9();
    void signalEnterStateTestSystemTemperature9();
    void signalEnterStateTestReadMAC9();
    void signalEnterStateTestReadSerial9();
    void signalEnterStateTestInternet9();
    void signalEnterStateTestInsulationResistance9();
    void signalEnterStateTestSoftWareVersion9();
    void signalEnterStateTestHardWareVersion9();
    void signalEnterStateTestSPI9();
    void signalEnterStateTestKB9();
    void signalEnterStateFinishTest9();
    void signalEnterStateExitTest9();

    void signalEnterStateStartTest10();
    void signalEnterStateTestSetBatteryVoltage10();
    void signalEnterStateTestSetHALLCurrent10();
    void signalEnterStateTestSetRTC10();
    void signalEnterStateTestSetMAC10();
    void signalEnterStateTestSetSerial10();
    void signalEnterStateTestZDResistance10();
    void signalEnterStateTestBatteryVoltage10();
    void signalEnterStateTestHALLCurrent10();
    void signalEnterStateTestSupplyVoltage10();
    void signalEnterStateTestPower10();
    void signalEnterStateTestHALLSignal10();
    void signalEnterStateTestTemperature10();
    void signalEnterStateTestEncodeInterface10();
    void signalEnterStateTestDO10();
    void signalEnterStateTestDIAndSLP10();
    void signalEnterStateTestSerialCommunication10();
    void signalEnterStateTestCANCommunication10();
    void signalEnterStateTestEEPROM10();
    void signalEnterStateTestFlash10();
    void signalEnterStateTestRTC10();
    void signalEnterStateTestSystemTemperature10();
    void signalEnterStateTestReadMAC10();
    void signalEnterStateTestReadSerial10();
    void signalEnterStateTestInternet10();
    void signalEnterStateTestInsulationResistance10();
    void signalEnterStateTestSoftWareVersion10();
    void signalEnterStateTestHardWareVersion10();
    void signalEnterStateTestSPI10();
    void signalEnterStateTestKB10();
    void signalEnterStateFinishTest10();
    void signalEnterStateExitTest10();

    void signalEnterStateStartTest11();
    void signalEnterStateTestSetBatteryVoltage11();
    void signalEnterStateTestSetHALLCurrent11();
    void signalEnterStateTestSetRTC11();
    void signalEnterStateTestSetMAC11();
    void signalEnterStateTestSetSerial11();
    void signalEnterStateTestZDResistance11();
    void signalEnterStateTestBatteryVoltage11();
    void signalEnterStateTestHALLCurrent11();
    void signalEnterStateTestSupplyVoltage11();
    void signalEnterStateTestPower11();
    void signalEnterStateTestHALLSignal11();
    void signalEnterStateTestTemperature11();
    void signalEnterStateTestEncodeInterface11();
    void signalEnterStateTestDO11();
    void signalEnterStateTestDIAndSLP11();
    void signalEnterStateTestSerialCommunication11();
    void signalEnterStateTestCANCommunication11();
    void signalEnterStateTestEEPROM11();
    void signalEnterStateTestFlash11();
    void signalEnterStateTestRTC11();
    void signalEnterStateTestSystemTemperature11();
    void signalEnterStateTestReadMAC11();
    void signalEnterStateTestReadSerial11();
    void signalEnterStateTestInternet11();
    void signalEnterStateTestInsulationResistance11();
    void signalEnterStateTestSoftWareVersion11();
    void signalEnterStateTestHardWareVersion11();
    void signalEnterStateTestSPI11();
    void signalEnterStateTestKB11();
    void signalEnterStateFinishTest11();
    void signalEnterStateExitTest11();

    void signalEnterStateStartTest12();
    void signalEnterStateTestSetBatteryVoltage12();
    void signalEnterStateTestSetHALLCurrent12();
    void signalEnterStateTestSetRTC12();
    void signalEnterStateTestSetMAC12();
    void signalEnterStateTestSetSerial12();
    void signalEnterStateTestZDResistance12();
    void signalEnterStateTestBatteryVoltage12();
    void signalEnterStateTestHALLCurrent12();
    void signalEnterStateTestSupplyVoltage12();
    void signalEnterStateTestPower12();
    void signalEnterStateTestHALLSignal12();
    void signalEnterStateTestTemperature12();
    void signalEnterStateTestEncodeInterface12();
    void signalEnterStateTestDO12();
    void signalEnterStateTestDIAndSLP12();
    void signalEnterStateTestSerialCommunication12();
    void signalEnterStateTestCANCommunication12();
    void signalEnterStateTestEEPROM12();
    void signalEnterStateTestFlash12();
    void signalEnterStateTestRTC12();
    void signalEnterStateTestSystemTemperature12();
    void signalEnterStateTestReadMAC12();
    void signalEnterStateTestReadSerial12();
    void signalEnterStateTestInternet12();
    void signalEnterStateTestInsulationResistance12();
    void signalEnterStateTestSoftWareVersion12();
    void signalEnterStateTestHardWareVersion12();
    void signalEnterStateTestSPI12();
    void signalEnterStateTestKB12();
    void signalEnterStateFinishTest12();
    void signalEnterStateExitTest12();

    void signalEnterStateStartTest13();
    void signalEnterStateTestSetBatteryVoltage13();
    void signalEnterStateTestSetHALLCurrent13();
    void signalEnterStateTestSetRTC13();
    void signalEnterStateTestSetMAC13();
    void signalEnterStateTestSetSerial13();
    void signalEnterStateTestZDResistance13();
    void signalEnterStateTestBatteryVoltage13();
    void signalEnterStateTestHALLCurrent13();
    void signalEnterStateTestSupplyVoltage13();
    void signalEnterStateTestPower13();
    void signalEnterStateTestHALLSignal13();
    void signalEnterStateTestTemperature13();
    void signalEnterStateTestEncodeInterface13();
    void signalEnterStateTestDO13();
    void signalEnterStateTestDIAndSLP13();
    void signalEnterStateTestSerialCommunication13();
    void signalEnterStateTestCANCommunication13();
    void signalEnterStateTestEEPROM13();
    void signalEnterStateTestFlash13();
    void signalEnterStateTestRTC13();
    void signalEnterStateTestSystemTemperature13();
    void signalEnterStateTestReadMAC13();
    void signalEnterStateTestReadSerial13();
    void signalEnterStateTestInternet13();
    void signalEnterStateTestInsulationResistance13();
    void signalEnterStateTestSoftWareVersion13();
    void signalEnterStateTestHardWareVersion13();
    void signalEnterStateTestSPI13();
    void signalEnterStateTestKB13();
    void signalEnterStateFinishTest13();
    void signalEnterStateExitTest13();

    void signalEnterStateStartTest14();
    void signalEnterStateTestSetBatteryVoltage14();
    void signalEnterStateTestSetHALLCurrent14();
    void signalEnterStateTestSetRTC14();
    void signalEnterStateTestSetMAC14();
    void signalEnterStateTestSetSerial14();
    void signalEnterStateTestZDResistance14();
    void signalEnterStateTestBatteryVoltage14();
    void signalEnterStateTestHALLCurrent14();
    void signalEnterStateTestSupplyVoltage14();
    void signalEnterStateTestPower14();
    void signalEnterStateTestHALLSignal14();
    void signalEnterStateTestTemperature14();
    void signalEnterStateTestEncodeInterface14();
    void signalEnterStateTestDO14();
    void signalEnterStateTestDIAndSLP14();
    void signalEnterStateTestSerialCommunication14();
    void signalEnterStateTestCANCommunication14();
    void signalEnterStateTestEEPROM14();
    void signalEnterStateTestFlash14();
    void signalEnterStateTestRTC14();
    void signalEnterStateTestSystemTemperature14();
    void signalEnterStateTestReadMAC14();
    void signalEnterStateTestReadSerial14();
    void signalEnterStateTestInternet14();
    void signalEnterStateTestInsulationResistance14();
    void signalEnterStateTestSoftWareVersion14();
    void signalEnterStateTestHardWareVersion14();
    void signalEnterStateTestSPI14();
    void signalEnterStateTestKB14();
    void signalEnterStateFinishTest14();
    void signalEnterStateExitTest14();

    void signalEnterStateStartTest15();
    void signalEnterStateTestSetBatteryVoltage15();
    void signalEnterStateTestSetHALLCurrent15();
    void signalEnterStateTestSetRTC15();
    void signalEnterStateTestSetMAC15();
    void signalEnterStateTestSetSerial15();
    void signalEnterStateTestZDResistance15();
    void signalEnterStateTestBatteryVoltage15();
    void signalEnterStateTestHALLCurrent15();
    void signalEnterStateTestSupplyVoltage15();
    void signalEnterStateTestPower15();
    void signalEnterStateTestHALLSignal15();
    void signalEnterStateTestTemperature15();
    void signalEnterStateTestEncodeInterface15();
    void signalEnterStateTestDO15();
    void signalEnterStateTestDIAndSLP15();
    void signalEnterStateTestSerialCommunication15();
    void signalEnterStateTestCANCommunication15();
    void signalEnterStateTestEEPROM15();
    void signalEnterStateTestFlash15();
    void signalEnterStateTestRTC15();
    void signalEnterStateTestSystemTemperature15();
    void signalEnterStateTestReadMAC15();
    void signalEnterStateTestReadSerial15();
    void signalEnterStateTestInternet15();
    void signalEnterStateTestInsulationResistance15();
    void signalEnterStateTestSoftWareVersion15();
    void signalEnterStateTestHardWareVersion15();
    void signalEnterStateTestSPI15();
    void signalEnterStateTestKB15();
    void signalEnterStateFinishTest15();
    void signalEnterStateExitTest15();

    void signalEnterStateStartTest16();
    void signalEnterStateTestSetBatteryVoltage16();
    void signalEnterStateTestSetHALLCurrent16();
    void signalEnterStateTestSetRTC16();
    void signalEnterStateTestSetMAC16();
    void signalEnterStateTestSetSerial16();
    void signalEnterStateTestZDResistance16();
    void signalEnterStateTestBatteryVoltage16();
    void signalEnterStateTestHALLCurrent16();
    void signalEnterStateTestSupplyVoltage16();
    void signalEnterStateTestPower16();
    void signalEnterStateTestHALLSignal16();
    void signalEnterStateTestTemperature16();
    void signalEnterStateTestEncodeInterface16();
    void signalEnterStateTestDO16();
    void signalEnterStateTestDIAndSLP16();
    void signalEnterStateTestSerialCommunication16();
    void signalEnterStateTestCANCommunication16();
    void signalEnterStateTestEEPROM16();
    void signalEnterStateTestFlash16();
    void signalEnterStateTestRTC16();
    void signalEnterStateTestSystemTemperature16();
    void signalEnterStateTestReadMAC16();
    void signalEnterStateTestReadSerial16();
    void signalEnterStateTestInternet16();
    void signalEnterStateTestInsulationResistance16();
    void signalEnterStateTestSoftWareVersion16();
    void signalEnterStateTestHardWareVersion16();
    void signalEnterStateTestSPI16();
    void signalEnterStateTestKB16();
    void signalEnterStateFinishTest16();
    void signalEnterStateExitTest16();

    void signalChangeItemBeforeFinish();
    void signalCreateExcel1(const QString &);
    void signalCreateExcel2(const QString &);
    void signalCreateExcel3(const QString &);
    void signalCreateExcel4(const QString &);
    void signalCreateExcel5(const QString &);
    void signalCreateExcel6(const QString &);
    void signalCreateExcel7(const QString &);
    void signalCreateExcel8(const QString &);
    void signalCreateExcel9(const QString &);
    void signalCreateExcel10(const QString &);
    void signalCreateExcel11(const QString &);
    void signalCreateExcel12(const QString &);
    void signalCreateExcel13(const QString &);
    void signalCreateExcel14(const QString &);
    void signalCreateExcel15(const QString &);
    void signalCreateExcel16(const QString &);
    void signalSetExcelItem1(std::vector<ExcelItem> items);
    void signalSetExcelItem2(std::vector<ExcelItem> items);
    void signalSetExcelItem3(std::vector<ExcelItem> items);
    void signalSetExcelItem4(std::vector<ExcelItem> items);
    void signalSetExcelItem5(std::vector<ExcelItem> items);
    void signalSetExcelItem6(std::vector<ExcelItem> items);
    void signalSetExcelItem7(std::vector<ExcelItem> items);
    void signalSetExcelItem8(std::vector<ExcelItem> items);
    void signalSetExcelItem9(std::vector<ExcelItem> items);
    void signalSetExcelItem10(std::vector<ExcelItem> items);
    void signalSetExcelItem11(std::vector<ExcelItem> items);
    void signalSetExcelItem12(std::vector<ExcelItem> items);
    void signalSetExcelItem13(std::vector<ExcelItem> items);
    void signalSetExcelItem14(std::vector<ExcelItem> items);
    void signalSetExcelItem15(std::vector<ExcelItem> items);
    void signalSetExcelItem16(std::vector<ExcelItem> items);
    void signalSetCurrentTestStep1(int);
    void signalSetCurrentTestStep2(int);
    void signalSetCurrentTestStep3(int);
    void signalSetCurrentTestStep4(int);
    void signalSetCurrentTestStep5(int);
    void signalSetCurrentTestStep6(int);
    void signalSetCurrentTestStep7(int);
    void signalSetCurrentTestStep8(int);
    void signalSetCurrentTestStep9(int);
    void signalSetCurrentTestStep10(int);
    void signalSetCurrentTestStep11(int);
    void signalSetCurrentTestStep12(int);
    void signalSetCurrentTestStep13(int);
    void signalSetCurrentTestStep14(int);
    void signalSetCurrentTestStep15(int);
    void signalSetCurrentTestStep16(int);
    void signalUpdateTestItem1();
    void signalUpdateTestItem2();
    void signalUpdateTestItem3();
    void signalUpdateTestItem4();
    void signalUpdateTestItem5();
    void signalUpdateTestItem6();
    void signalUpdateTestItem7();
    void signalUpdateTestItem8();
    void signalUpdateTestItem9();
    void signalUpdateTestItem10();
    void signalUpdateTestItem11();
    void signalUpdateTestItem12();
    void signalUpdateTestItem13();
    void signalUpdateTestItem14();
    void signalUpdateTestItem15();
    void signalUpdateTestItem16();
    void signalStartTest();
    void signalErrorSerial(QString);
    void signalSetMod();
    void signalSendJsonData(QJsonObject);
};

#endif // MAINCONTROL_H
