#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <vector>
#include <chrono>
#include <QKeyEvent>
#include <QJsonObject>
#include "model/testItemEnums.h"
#include "controller/serialportcontroller.h"
#include "controller/excelcontrol.h"

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class QTimer;
class QCheckBox;
class MACDialog;
class SerialDialog;
class QTimer;
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    MainWindow(const MainWindow &) = default;
    MainWindow(MainWindow &&) = delete;
    MainWindow &operator=(const MainWindow &) = default;
    MainWindow &operator=(MainWindow &&) = delete;
    ~MainWindow();
    void setWindowType(bool mod, int type1, int type2, int type3, int type4, int type5
                       , int type6, int type7, int type8, int type9, int type10
                       , int type11, int type12, int type13, int type14, int type15, int type16);
    void setCurrentItem1(int type);
    void setCurrentItem2(int type);
    void setCurrentItem3(int type);
    void setCurrentItem4(int type);
    void setCurrentItem5(int type);
    void setCurrentItem6(int type);
    void setCurrentItem7(int type);
    void setCurrentItem8(int type);
    void setCurrentItem9(int type);
    void setCurrentItem10(int type);
    void setCurrentItem11(int type);
    void setCurrentItem12(int type);
    void setCurrentItem13(int type);
    void setCurrentItem14(int type);
    void setCurrentItem15(int type);
    void setCurrentItem16(int type);
    void updateView1();
    void updateView2();
    void updateView3();
    void updateView4();
    void updateView5();
    void updateView6();
    void updateView7();
    void updateView8();
    void updateView9();
    void updateView10();
    void updateView11();
    void updateView12();
    void updateView13();
    void updateView14();
    void updateView15();
    void updateView16();

private:
    void layoutUI();
    void connectFunc();
    void initTabelWidet();
    void readIni();

private:
    Ui::MainWindow *ui;
    TestItem currentItem1 = StartTest;
    TestItem currentItem2 = StartTest;
    TestItem currentItem3 = StartTest;
    TestItem currentItem4 = StartTest;
    TestItem currentItem5 = StartTest;
    TestItem currentItem6 = StartTest;
    TestItem currentItem7 = StartTest;
    TestItem currentItem8 = StartTest;
    TestItem currentItem9 = StartTest;
    TestItem currentItem10 = StartTest;
    TestItem currentItem11 = StartTest;
    TestItem currentItem12 = StartTest;
    TestItem currentItem13 = StartTest;
    TestItem currentItem14 = StartTest;
    TestItem currentItem15 = StartTest;
    TestItem currentItem16 = StartTest;
    QTimer *reTryTimer;
    int reTryNumber;
    bool ifSwitch = false;
    bool ifManual = false;
    int m_row = 0;
    int m_col = 0;
    std::vector<QCheckBox*> checkBoxs1;
    std::vector<QCheckBox*> checkBoxs2;
    std::vector<QCheckBox*> checkBoxs3;
    std::vector<QCheckBox*> checkBoxs4;
    std::vector<QCheckBox*> checkBoxs5;
    std::vector<QCheckBox*> checkBoxs6;
    std::vector<QCheckBox*> checkBoxs7;
    std::vector<QCheckBox*> checkBoxs8;
    std::vector<QCheckBox*> checkBoxs9;
    std::vector<QCheckBox*> checkBoxs10;
    std::vector<QCheckBox*> checkBoxs11;
    std::vector<QCheckBox*> checkBoxs12;
    std::vector<QCheckBox*> checkBoxs13;
    std::vector<QCheckBox*> checkBoxs14;
    std::vector<QCheckBox*> checkBoxs15;
    std::vector<QCheckBox*> checkBoxs16;
    std::chrono::high_resolution_clock::time_point t01;
    std::chrono::high_resolution_clock::time_point t11;
    std::chrono::high_resolution_clock::time_point t02;
    std::chrono::high_resolution_clock::time_point t12;
    std::chrono::high_resolution_clock::time_point t03;
    std::chrono::high_resolution_clock::time_point t13;
    std::chrono::high_resolution_clock::time_point t04;
    std::chrono::high_resolution_clock::time_point t14;
    std::chrono::high_resolution_clock::time_point t05;
    std::chrono::high_resolution_clock::time_point t15;
    std::chrono::high_resolution_clock::time_point t06;
    std::chrono::high_resolution_clock::time_point t16;
    std::chrono::high_resolution_clock::time_point t07;
    std::chrono::high_resolution_clock::time_point t17;
    std::chrono::high_resolution_clock::time_point t08;
    std::chrono::high_resolution_clock::time_point t18;
    std::chrono::high_resolution_clock::time_point t09;
    std::chrono::high_resolution_clock::time_point t19;
    std::chrono::high_resolution_clock::time_point t010;
    std::chrono::high_resolution_clock::time_point t110;
    std::chrono::high_resolution_clock::time_point t011;
    std::chrono::high_resolution_clock::time_point t111;
    std::chrono::high_resolution_clock::time_point t012;
    std::chrono::high_resolution_clock::time_point t112;
    std::chrono::high_resolution_clock::time_point t013;
    std::chrono::high_resolution_clock::time_point t113;
    std::chrono::high_resolution_clock::time_point t014;
    std::chrono::high_resolution_clock::time_point t114;
    std::chrono::high_resolution_clock::time_point t015;
    std::chrono::high_resolution_clock::time_point t115;
    std::chrono::high_resolution_clock::time_point t016;
    std::chrono::high_resolution_clock::time_point t116;
    std::vector<ExcelItem> items1;
    std::vector<ExcelItem> items2;
    std::vector<ExcelItem> items3;
    std::vector<ExcelItem> items4;
    std::vector<ExcelItem> items5;
    std::vector<ExcelItem> items6;
    std::vector<ExcelItem> items7;
    std::vector<ExcelItem> items8;
    std::vector<ExcelItem> items9;
    std::vector<ExcelItem> items10;
    std::vector<ExcelItem> items11;
    std::vector<ExcelItem> items12;
    std::vector<ExcelItem> items13;
    std::vector<ExcelItem> items14;
    std::vector<ExcelItem> items15;
    std::vector<ExcelItem> items16;
    int m_type1 = 0;
    int m_type2 = 0;
    int m_type3 = 0;
    int m_type4 = 0;
    int m_type5 = 0;
    int m_type6 = 0;
    int m_type7 = 0;
    int m_type8 = 0;
    int m_type9 = 0;
    int m_type10 = 0;
    int m_type11 = 0;
    int m_type12 = 0;
    int m_type13 = 0;
    int m_type14 = 0;
    int m_type15 = 0;
    int m_type16 = 0;
    int mac_type = 0;
    bool if_testing1 = false;
    bool if_testing2 = false;
    bool if_testing3 = false;
    bool if_testing4 = false;
    bool if_testing5 = false;
    bool if_testing6 = false;
    bool if_testing7 = false;
    bool if_testing8 = false;
    bool if_testing9 = false;
    bool if_testing10 = false;
    bool if_testing11 = false;
    bool if_testing12 = false;
    bool if_testing13 = false;
    bool if_testing14 = false;
    bool if_testing15 = false;
    bool if_testing16 = false;
    bool readyToUpdate1 = false;
    bool readyToUpdate2 = false;
    bool readyToUpdate3 = false;
    bool readyToUpdate4 = false;
    bool readyToUpdate5 = false;
    bool readyToUpdate6 = false;
    bool readyToUpdate7 = false;
    bool readyToUpdate8 = false;
    bool readyToUpdate9 = false;
    bool readyToUpdate10 = false;
    bool readyToUpdate11 = false;
    bool readyToUpdate12 = false;
    bool readyToUpdate13 = false;
    bool readyToUpdate14 = false;
    bool readyToUpdate15 = false;
    bool readyToUpdate16 = false;
    MACDialog *macDialog;
    SerialDialog *serialDialog;
    QTimer *testTimer1;
    QTimer *testTimer2;
    QTimer *testTimer3;
    QTimer *testTimer4;
    QTimer *testTimer5;
    QTimer *testTimer6;
    QTimer *testTimer7;
    QTimer *testTimer8;
    QTimer *testTimer9;
    QTimer *testTimer10;
    QTimer *testTimer11;
    QTimer *testTimer12;
    QTimer *testTimer13;
    QTimer *testTimer14;
    QTimer *testTimer15;
    QTimer *testTimer16;
    bool m_mod = false;
    QJsonObject testresult1;
    QJsonObject testresult2;
    QJsonObject testresult3;
    QJsonObject testresult4;
    QJsonObject testresult5;
    QJsonObject testresult6;
    QJsonObject testresult7;
    QJsonObject testresult8;
    QJsonObject testresult9;
    QJsonObject testresult10;
    QJsonObject testresult11;
    QJsonObject testresult12;
    QJsonObject testresult13;
    QJsonObject testresult14;
    QJsonObject testresult15;
    QJsonObject testresult16;
    int testNum = 0;
    QTimer *failTimer1;
    QTimer *failTimer2;
    QTimer *failTimer3;
    QTimer *failTimer4;
    QTimer *failTimer5;
    QTimer *failTimer6;
    QTimer *failTimer7;
    QTimer *failTimer8;
    QTimer *failTimer9;
    QTimer *failTimer10;
    QTimer *failTimer11;
    QTimer *failTimer12;
    QTimer *failTimer13;
    QTimer *failTimer14;
    QTimer *failTimer15;
    QTimer *failTimer16;
    SerialPortController *controller;
    int totalTest1 = 0;
    int totalTest2 = 0;
    int totalTest3 = 0;
    int totalTest4 = 0;
    int totalTest5 = 0;
    int totalTest6 = 0;
    int totalTest7 = 0;
    int totalTest8 = 0;
    int totalTest9 = 0;
    int totalTest10 = 0;
    int totalTest11 = 0;
    int totalTest12 = 0;
    int totalTest13 = 0;
    int totalTest14 = 0;
    int totalTest15 = 0;
    int totalTest16 = 0;
    int NGTest1 = 0;
    int NGTest2 = 0;
    int NGTest3 = 0;
    int NGTest4 = 0;
    int NGTest5 = 0;
    int NGTest6 = 0;
    int NGTest7 = 0;
    int NGTest8 = 0;
    int NGTest9 = 0;
    int NGTest10 = 0;
    int NGTest11 = 0;
    int NGTest12 = 0;
    int NGTest13 = 0;
    int NGTest14 = 0;
    int NGTest15 = 0;
    int NGTest16 = 0;
    int successTest1 = 0;
    int successTest2 = 0;
    int successTest3 = 0;
    int successTest4 = 0;
    int successTest5 = 0;
    int successTest6 = 0;
    int successTest7 = 0;
    int successTest8 = 0;
    int successTest9 = 0;
    int successTest10 = 0;
    int successTest11 = 0;
    int successTest12 = 0;
    int successTest13 = 0;
    int successTest14 = 0;
    int successTest15 = 0;
    int successTest16 = 0;
    bool ifSuccess1 = true;
    bool ifSuccess2 = true;
    bool ifSuccess3 = true;
    bool ifSuccess4 = true;
    bool ifSuccess5 = true;
    bool ifSuccess6 = true;
    bool ifSuccess7 = true;
    bool ifSuccess8 = true;
    bool ifSuccess9 = true;
    bool ifSuccess10 = true;
    bool ifSuccess11 = true;
    bool ifSuccess12 = true;
    bool ifSuccess13 = true;
    bool ifSuccess14 = true;
    bool ifSuccess15 = true;
    bool ifSuccess16 = true;

protected:
    bool eventFilter(QObject *obj, QEvent *event);

public slots:
    void slotOpenConnectDevicePage();
    void slotAppendStatus1(const QString & status);
    void slotAppendStatus2(const QString & status);
    void slotAppendStatus3(const QString & status);
    void slotAppendStatus4(const QString & status);
    void slotAppendStatus5(const QString & status);
    void slotAppendStatus6(const QString & status);
    void slotAppendStatus7(const QString & status);
    void slotAppendStatus8(const QString & status);
    void slotAppendStatus9(const QString & status);
    void slotAppendStatus10(const QString & status);
    void slotAppendStatus11(const QString & status);
    void slotAppendStatus12(const QString & status);
    void slotAppendStatus13(const QString & status);
    void slotAppendStatus14(const QString & status);
    void slotAppendStatus15(const QString & status);
    void slotAppendStatus16(const QString & status);
    void slotShowErrorStatus(const QString &status);
    void slotChangeConnectStatus();
    void slotCloseCAN();
    void slotChangeItemBeforeFinish();
    void slotStartTest1();
    void slotStartTest2();
    void slotStartTest3();
    void slotStartTest4();
    void slotStartTest5();
    void slotStartTest6();
    void slotStartTest7();
    void slotStartTest8();
    void slotStartTest9();
    void slotStartTest10();
    void slotStartTest11();
    void slotStartTest12();
    void slotStartTest13();
    void slotStartTest14();
    void slotStartTest15();
    void slotStartTest16();
    void slotSaveData1();
    void slotSaveData2();
    void slotSaveData3();
    void slotSaveData4();
    void slotSaveData5();
    void slotSaveData6();
    void slotSaveData7();
    void slotSaveData8();
    void slotSaveData9();
    void slotSaveData10();
    void slotSaveData11();
    void slotSaveData12();
    void slotSaveData13();
    void slotSaveData14();
    void slotSaveData15();
    void slotSaveData16();
    void slotContinue1();
    void slotContinue2();
    void slotContinue3();
    void slotContinue4();
    void slotContinue5();
    void slotContinue6();
    void slotContinue7();
    void slotContinue8();
    void slotContinue9();
    void slotContinue10();
    void slotContinue11();
    void slotContinue12();
    void slotContinue13();
    void slotContinue14();
    void slotContinue15();
    void slotContinue16();
    void slotChangeIcon(int lenth);
    void slotIfContuine(int ifContuine);
    void slotCellClicked(int row, int col);
    void slotFinish1();
    void slotFinish2();
    void slotFinish3();
    void slotFinish4();
    void slotFinish5();
    void slotFinish6();
    void slotFinish7();
    void slotFinish8();
    void slotFinish9();
    void slotFinish10();
    void slotFinish11();
    void slotFinish12();
    void slotFinish13();
    void slotFinish14();
    void slotFinish15();
    void slotFinish16();
    void slotErrorFinish1();
    void slotErrorFinish2();
    void slotErrorFinish3();
    void slotErrorFinish4();
    void slotErrorFinish5();
    void slotErrorFinish6();
    void slotErrorFinish7();
    void slotErrorFinish8();
    void slotErrorFinish9();
    void slotErrorFinish10();
    void slotErrorFinish11();
    void slotErrorFinish12();
    void slotErrorFinish13();
    void slotErrorFinish14();
    void slotErrorFinish15();
    void slotErrorFinish16();
    void slotSignleTest();
    void slotSelectAll();
    void slotSelectAll2();
    void slotSelectAll3();
    void slotSelectAll4();
    void slotSelectAll5();
    void slotSelectAll6();
    void slotSelectAll7();
    void slotSelectAll8();
    void slotSelectAll9();
    void slotSelectAll10();
    void slotSelectAll11();
    void slotSelectAll12();
    void slotSelectAll13();
    void slotSelectAll14();
    void slotSelectAll15();
    void slotSelectAll16();
    void slotReadData();
    void slotReceiveMAC1(QString mac);
    void slotReceiveMAC2(QString mac);
    void slotReceiveMAC3(QString mac);
    void slotReceiveMAC4(QString mac);
    void slotReceiveMAC5(QString mac);
    void slotReceiveMAC6(QString mac);
    void slotReceiveMAC7(QString mac);
    void slotReceiveMAC8(QString mac);
    void slotReceiveMAC9(QString mac);
    void slotReceiveMAC10(QString mac);
    void slotReceiveMAC11(QString mac);
    void slotReceiveMAC12(QString mac);
    void slotReceiveMAC13(QString mac);
    void slotReceiveMAC14(QString mac);
    void slotReceiveMAC15(QString mac);
    void slotReceiveMAC16(QString mac);
    void slotChangeMAC(const QString &mac);
    void slotChangeSerial(const QString &serial);
    void slotReceiveSerial1(QString serial);
    void slotReceiveSerial2(QString serial);
    void slotReceiveSerial3(QString serial);
    void slotReceiveSerial4(QString serial);
    void slotReceiveSerial5(QString serial);
    void slotReceiveSerial6(QString serial);
    void slotReceiveSerial7(QString serial);
    void slotReceiveSerial8(QString serial);
    void slotReceiveSerial9(QString serial);
    void slotReceiveSerial10(QString serial);
    void slotReceiveSerial11(QString serial);
    void slotReceiveSerial12(QString serial);
    void slotReceiveSerial13(QString serial);
    void slotReceiveSerial14(QString serial);
    void slotReceiveSerial15(QString serial);
    void slotReceiveSerial16(QString serial);
    void slotTryEnterAdminMod();
    void slotEnableSelectAll();
    void slotChangeSelectAll();
    void slotOpenCheckPage();
    void slotSetMac();
    void slotSetSerial();
    void slotReadKB(int type, int locate);
    void slotSetKB(int type, float k, float b, int locate);
    void slotGetKB(float k, float b);
    void slotReadInfo(int type, int locate);
    void slotGetInfo(int a, float b, int locate);
    void slotOpenDO(int locate);
    void slotCloseDO(int locate);
    void slotSendMAC();
    void slotSendSerial();
    void slotAddTime1();
    void slotAddTime2();
    void slotAddTime3();
    void slotAddTime4();
    void slotAddTime5();
    void slotAddTime6();
    void slotAddTime7();
    void slotAddTime8();
    void slotAddTime9();
    void slotAddTime10();
    void slotAddTime11();
    void slotAddTime12();
    void slotAddTime13();
    void slotAddTime14();
    void slotAddTime15();
    void slotAddTime16();
    void slotSerialEnter();
    void slotMACEnter();
    void slotStartMesTest();
    void slotErrorSerial(QString log);
    void slotGetGDList();
    void slotReceiveGDList(const QStringList &);
    void slotResult(bool result);
    void slotGetVersion(const QString &hard, const QString &soft);
    void slotChangeUI();
    void slotShowVersion();
    void slotEEPROMFinish();
    void slotEEPROMErrorFinish();
    void slotFlashFinish();
    void slotFlashErrorFinish();
    void slotRTCFinish();
    void slotRTCErrorFinish();
    void slotIOErrorFinish();
    void slotIOFinish();
    void slotDIErrorFinish();
    void slotDOErrorFinish();
    void slotDIFinish();
    void slotDOFinish();
    void slotCANFinish();
    void slotCANErrorFinish();
    void slotSerialFinish();
    void slotSerialErrorFinish();
    void slotHALLCurrentFinish();
    void slotHALLCurrentErrorFinish();
    void slotBatteryVoltageFinish();
    void slotBatteryVoltageErrorFinish();
    void slotSupplyVoltageFinish();
    void slotSupplyVoltageErrorFinish();
    void slotSystemTemperatureFinish();
    void slotSystemTemperatureErrorFinish();
    void slotInsulationResistanceFinish();
    void slotInsulationResistanceErrorFinish();
    void slotPowerFinish();
    void slotPowerErrorFinish();
    void slotHALLSignalFinish();
    void slotHALLSignalErrorFinish();
    void slotTemperatureErrorFinish();
    void slotTemperatureFinish();
    void slotNetError();
    void slotSetModFail1();
    void slotSetModFail2();
    void slotSetModFail3();
    void slotSetModFail4();
    void slotSetModFail5();
    void slotSetModFail6();
    void slotSetModFail7();
    void slotSetModFail8();
    void slotSetModFail9();
    void slotSetModFail10();
    void slotSetModFail11();
    void slotSetModFail12();
    void slotSetModFail13();
    void slotSetModFail14();
    void slotSetModFail15();
    void slotSetModFail16();
    void slotTimeOut1();
    void slotTimeOut2();
    void slotTimeOut3();
    void slotTimeOut4();
    void slotTimeOut5();
    void slotTimeOut6();
    void slotTimeOut7();
    void slotTimeOut8();
    void slotTimeOut9();
    void slotTimeOut10();
    void slotTimeOut11();
    void slotTimeOut12();
    void slotTimeOut13();
    void slotTimeOut14();
    void slotTimeOut15();
    void slotTimeOut16();
    void slotSetDetial(QString detial);
    void slotTestMac();
    void slotOpenConnPage();
    void slotStartSeriolPort(const QString &id, int port);
    void slotSerialError1();
    void slotSerialError2();
    void slotSerialError3();
    void slotSerialError4();
    void slotSerialError5();
    void slotSerialError6();
    void slotSerialError7();
    void slotSerialError8();
    void slotSerialError9();
    void slotSerialError10();
    void slotSerialError11();
    void slotSerialError12();
    void slotSerialError13();
    void slotSerialError14();
    void slotSerialError15();
    void slotSerialError16();
    void slotChange(int type, int locate);
    void slotChangeTo1();
    void slotChangeTo2();
    void slotChangeTo3();
    void slotChangeTo4();
    void slotChangeTo5();
    void slotChangeTo6();
    void slotChangeTo7();
    void slotChangeTo8();
    void slotChangeTo9();
    void slotChangeTo10();
    void slotChangeTo11();
    void slotChangeTo12();
    void slotChangeTo13();
    void slotChangeTo14();
    void slotChangeTo15();
    void slotChangeTo16();
    void slotChangeDetial(int detial);

signals:
    void signalOpenConnectDevicePage();
    void signalCloseCAN();
    void signalTryUpadateStates1(int);
    void signalTryUpadateStates2(int);
    void signalTryUpadateStates3(int);
    void signalTryUpadateStates4(int);
    void signalTryUpadateStates5(int);
    void signalTryUpadateStates6(int);
    void signalTryUpadateStates7(int);
    void signalTryUpadateStates8(int);
    void signalTryUpadateStates9(int);
    void signalTryUpadateStates10(int);
    void signalTryUpadateStates11(int);
    void signalTryUpadateStates12(int);
    void signalTryUpadateStates13(int);
    void signalTryUpadateStates14(int);
    void signalTryUpadateStates15(int);
    void signalTryUpadateStates16(int);
    void signalStartTest1();
    void signalStartTest2();
    void signalStartTest3();
    void signalStartTest4();
    void signalStartTest5();
    void signalStartTest6();
    void signalStartTest7();
    void signalStartTest8();
    void signalStartTest9();
    void signalStartTest10();
    void signalStartTest11();
    void signalStartTest12();
    void signalStartTest13();
    void signalStartTest14();
    void signalStartTest15();
    void signalStartTest16();
    void signalIfContuine(int);
    void signalSaveData1(std::vector<ExcelItem>);
    void signalSaveData2(std::vector<ExcelItem>);
    void signalSaveData3(std::vector<ExcelItem>);
    void signalSaveData4(std::vector<ExcelItem>);
    void signalSaveData5(std::vector<ExcelItem>);
    void signalSaveData6(std::vector<ExcelItem>);
    void signalSaveData7(std::vector<ExcelItem>);
    void signalSaveData8(std::vector<ExcelItem>);
    void signalSaveData9(std::vector<ExcelItem>);
    void signalSaveData10(std::vector<ExcelItem>);
    void signalSaveData11(std::vector<ExcelItem>);
    void signalSaveData12(std::vector<ExcelItem>);
    void signalSaveData13(std::vector<ExcelItem>);
    void signalSaveData14(std::vector<ExcelItem>);
    void signalSaveData15(std::vector<ExcelItem>);
    void signalSaveData16(std::vector<ExcelItem>);
    void signalStartSelfCheck();
    void signalSetMac(const QString &);
    void signalSetSerial(const QString &);
    void signalReadKB(int, int, int locate);
    void signalSetKB(int, int, float k, float b, int locate);
    void signalGetKB(float k, float b);
    void signalReadInfo(int type, int locate);
    void signalGetInfo(int, float, int);
    void signalOpenDO(int locate);
    void signalCloseDO(int locate);
    void signalSetSoft(const QString &);
    void signalSetHard(const QString &);
    void signalTestResult1(bool);
    void signalTestResult2(bool);
    void signalTestResult3(bool);
    void signalTestResult4(bool);
    void signalTestResult5(bool);
    void signalTestResult6(bool);
    void signalTestResult7(bool);
    void signalTestResult8(bool);
    void signalTestResult9(bool);
    void signalTestResult10(bool);
    void signalTestResult11(bool);
    void signalTestResult12(bool);
    void signalTestResult13(bool);
    void signalTestResult14(bool);
    void signalTestResult15(bool);
    void signalTestResult16(bool);
    void signalGetGDList();
    void signalSendSerialList(const QString &, const QString &, const QString &, const QString &, const QString &);
    void signalSendTester(const QString&);
    void signalSendTestResult1(QJsonObject);
    void signalSendTestResult2(QJsonObject);
    void signalSendTestResult3(QJsonObject);
    void signalSendTestResult4(QJsonObject);
    void signalSendTestResult5(QJsonObject);
    void signalSendTestResult6(QJsonObject);
    void signalSendTestResult7(QJsonObject);
    void signalSendTestResult8(QJsonObject);
    void signalSendTestResult9(QJsonObject);
    void signalSendTestResult10(QJsonObject);
    void signalSendTestResult11(QJsonObject);
    void signalSendTestResult12(QJsonObject);
    void signalSendTestResult13(QJsonObject);
    void signalSendTestResult14(QJsonObject);
    void signalSendTestResult15(QJsonObject);
    void signalSendTestResult16(QJsonObject);
    void signalGetVersion(QJsonObject);
    void signalStartSerialPort(const QString &, int);
    void signalChange(int type, int locate);
    void signalSetGD(QString);
};
#endif // MAINWINDOW_H
